### ISSUE TITLE
Json generation for collection of decorated objects

### ISSUE THREAD

**Issue by angelim** [drapergem/draper#101]
If anyone is also having trouble generating json from decorated collections, I suggest you override `#as_json` on your decorator or ApplicationDecorator to call the respective model `#as_json`.

```
class ApplicationDecorator < Draper::Base
  def as_json(options = {})
    model.as_json(options)
  end
end
```

 If you want to provide default options for json generation, I recommend overriding #to_json as well, so you can keep single record and collection json generation consistent.

```
def to_json(options = {})
  as_json(options).to_json
end
```

If you're interested in extending json generation to use methods defined inside your decorators(this is helpful for me, at least) you can checkout my lastest commit and extract some ideas from there (https://github.com/angelim/draper-1/commit/3dfbf3b50fda193cdf6727f7d8edb7560e442150)

**Be careful with association support, though**. Draper doesn't support `#decorate_association` yet and this snippet is using some features that are exclusive to my fork.

I hope this helps someone.

**Comment by tden012** [comment]
This comment is a bit late, but I thought I'd add a solution that didn't involve forking. As mentioned by angelim, it's possible to create an ApplicationDecorator in order to add the methods necessary to add decorator methods to json. This is what mine looks like (it's more or less a complete copy of angelim's code)

```ruby
class ApplicationDecorator < Draper::Decorator
  def as_json(options = {})
    as_decorated_json(options)
  end

  def to_json(options = {})
    as_json(options)
  end
  
  def as_decorated_json(options = {})
    model.as_json(options).merge(decorated_attributes(options))
  end
  
  def decorated_attributes(options = {})
    method_names = Array.wrap(options[:decorated_methods]).map { |n| n.to_s if respond_to?(n.to_s) }.compact
    Hash[method_names.map { |n| [n, send(n)] }].tap do |attrs|
      decorate_relations(attrs, options) if options[:decorated_include]
    end
  end
  
  def add_decorated_methods(options, method_names = [])
    options[:decorated_methods] = options[:decorated_methods] ? options[:decorated_methods] : []
    options[:decorated_methods].concat method_names
  end
end
```

Note the last method. This is useful if you want to make the model always render certain decorator methods in json. E.g.

```ruby
class ModelDecorator < ApplicationDecorator
  delegate_all

  def my_decorator_method
    names[0]
  end
  
  def as_json(options = {})
    add_decorated_methods options, [:my_decorator_method]
    super options
  end
end
```
