### ISSUE TITLE
NoMethodError undefined method `host' for nil:NilClass (not in tests)

### ISSUE THREAD

**Issue by shimms** [drapergem/draper#256]
We're getting an intermittent error with with a Draper decorator accessing any route.

Trying to access a route within the Decorate:

```
h.material_path(child.space, child)
```

Results in the error:

```
NoMethodError - undefined method `host' for nil:NilClass
```

Backtrace

```
[GEM_ROOT]/gems/actionpack-3.2.8/lib/action_controller/metal/url_for.rb:30url_options
[GEM_ROOT]/gems/actionpack-3.2.8/lib/action_view/helpers/url_helper.rb:37url_options
[GEM_ROOT]/gems/actionpack-3.2.8/lib/action_dispatch/routing/url_for.rb:148url_for
[GEM_ROOT]/gems/actionpack-3.2.8/lib/action_view/helpers/url_helper.rb:107url_for
[GEM_ROOT]/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:213material_path
[PROJECT_ROOT]/app/decorators/material_decorator.rb:16block in json_for_tree
```

Any request that access routes seems to cause this error, but only sometimes (20% of the time roughly). Other times it works as expected.

**Comment by nisevi** [comment]
Was this fixed? Or we just add?:

```ruby
include Rails.application.routes.url_helpers
```

To our decorator classes in order to fix it?

**Comment by sekrett** [comment]
It worked for me but I believe it got broken again after I did a `bundle update`. So I ended with:

```ruby
class ApplicationDecorator < Draper::Decorator
  def host
    Rails.application.config.action_mailer.default_url_options[:host]
  end
end
```

Then I pass `host` through `locals` and pass it to every url helper. Ugly but it works.

**Comment by msxavi** [comment]
I'm having this issue on Ruby 3.2, Rails 7.1, Draper 4.0.2. It also happens randomly 1 out of 6 times even after adding `include Rails.application.routes.url_helpers`. Quite strange.

**Comment by Alexander-Senko** [comment]
I believe this to happen due to an implementation of a _view context_ and _helpers_. I started rewriting it some time ago, but... See https://github.com/drapergem/draper/issues/921#issuecomment-2533527761 on it.

**Comment by gamesover** [comment]
> I believe this to happen due to an implementation of a _view context_ and _helpers_. I started rewriting it some time ago, but... See [#921 (comment)](https://github.com/drapergem/draper/issues/921#issuecomment-2533527761) on it.

Based on my experience, `Draper` seems to cache the `request` object internally. Since our application frequently clears `Thread.current`, Draper eventually loses access to the request, which causes errors when calling r`equest.host`—whether through `Rails` or `Draper`.

It's a particularly frustrating bug.

**Comment by Alexander-Senko** [comment]
@gamesover, thanks for your guess!

I’ve rewritten handling of a _view context_ completely while refactoring Draper into [Magic Presenter](https://github.com/Alexander-Senko/magic-presenter#view-context). There is no need to cache _requests_ or handle them directly in any other way.

IMO, Draper does a lot of stuff internally that could be opted out completely or done in a less coupling way. That makes it brittle and leads to a lot of recurring bugs here and there.

I’ve already solved those all the known issues in my [Magic Presenter](https://github.com/Alexander-Senko/magic-presenter), but I still see absolutely no interest in moving Draper in that direction unfortunately.
