### ISSUE TITLE
Draper with pagination

### ISSUE THREAD

**Issue by arunsark** [drapergem/draper#30]
I am using will_paginate to paginate the results.
How do we decorate model objects in this case?

In my controller I give something like this

@articles = ArticleDecorator.decorate(Article.paginate(:page => params[:page], :per_page => 5))

But it gives me an error undefined method `total_pages' for #Array:0x9a81e94

Is there any workaround for this?

**Comment by SaimonL** [comment]
> You can keep decorators in the view layer. For example.
> 
> ```
> # controller
> @articles = Article.paginate(:page => params[:page], :per_page => 5)
> 
> # view
> <% ArticleDecorator.decorate_each(@articles) do |article| %>
>   <%= article.name %>
> <% end %>
> 
> # ArticleDecorator
> def self.decorate_each(objects)
>   objects.each do |object|
>     yield decorate(object)
>   end
> end
> ```
> 
> Perhaps some better way to initialize decorators in the view can be added to draper to make this easier?

This worked for me
```ruby
<% ProjectDecorator.decorate_collection(projects).each do |project| %>
  <%= project.some_decorate_function %>
<% end %>
