### ISSUE TITLE
Draper and Haml Helpers

### ISSUE THREAD

**Issue by Veejay** [drapergem/draper#323]
I use Draper in my code to produce components for my models (user badges, recaps, profile elements, etc). 

To that effect, I like using haml helpers. According to Haml::Helpers' documentation 

> Helpers is automatically included in the context that a Haml template is parsed in, so all these 
> methods are at your disposal from within the template.

In the context of a decorator now, I need to include Haml::Helpers and then call init_haml_helpers (see http://haml.info/docs/yardoc/Haml/Helpers.html#init_haml_helpers-instance_method).

This is not the end of the world, but it'd make sense for those helpers to be automatically available in a decorator (or at least does to me :smiley:), or to make Draper decorators more "akin" to an ActionView context.

Thanks and great job on Draper guys.

**Comment by jcasimir** [comment]
Closing for age, reopen if necessary.

**Comment by nicpillinger** [comment]
hey, this still seems to be a problem with 2.1.0?
I'm having to include haml helpers and call init on them to see them available in my decorator. Did this issue ever get fixed, it looks like it might have worked with older versions from the comments above but it doesn't seem to now - if I use a simple example as described above using capture_haml it cant see the method.

**Comment by asadakbarml** [comment]
In case anyone else gets here, this is still an issue for me on rails 5.2 and haml-rails 2.0.1.
