### ISSUE TITLE
Adding more parameters to decorator parameters

### ISSUE THREAD

**Issue by mb-dev** [drapergem/draper#339]
Is there a way to pass more parameters to decorator constructor?

I am interested to pass other than the instance - some meta data that i pre populated in the controller.

**Comment by ndnenkov** [comment]
Note for future readers - for newer versions of the gem your metadata should be under `context`:

```ruby
product = Product.find(product_id)
decorator = ProductDecorator.new(product, context: {some: 'metadata'})

decorator.context # => {some: 'metadata'}
```
