### ISSUE TITLE
Kaminari vs Draper

### ISSUE THREAD

**Issue by tovodeverett** [drapergem/draper#401]
Now I'm poking at another issue (trying to resolve all the non-`==` issues before focusing on that one).

I'm using kaminari (https://github.com/amatsuda/kaminari) in this project.  After moving to Draper 1.0.0.beta5, I'm also getting errors from the pagination code.  Here's the rough code flow in the Controller/View:
- Retrieve list of objects using something like `models = Model.order('foo').page(params[:page]).per(25)`
- Decorate the list of objects using something like `@models = ModelsDecorator.new(models, context: context)`
- Render the objects in the view and at the end add the pagination links: `= paginate @models`

The paginate helper in turn relies upon `current_page`, `total_pages`, and `limit_value`, which get added by the call to `page` in the first line.  I suspect kaminari extends the `ActiveRecord::Relation` object.

I'm trying to figure out how best to resolve the issue.  The initial pagination needs to occur when retrieving the model objects in order to avoid loading more objects than is necessary from the database.  I can easily add custom code in `ModelsDecorator` to delegate those methods, but unless I wrap around initialize, there's nothing in the Decorator that points to the actual Relation (as opposed to the Array grabbed from it).  Thoughts?

My instinct is to suggest that we hang on to the original source object and stash it somewhere in the CollectionDecorator instance and then provide a private read-only accessor for it.  I don't think we're going to be able to avoid supporting direct access to the original, unfrozen, source object.  But by marking it private, we force the delegation to be done explicitly by the user.  We can also add appropriate documentation indicating that only non-mutating methods should be called and that if those calls return model objects, they need to be explicitly decorated.  If we go down this approach, we can also delay the calls to `.to_a.dup.freeze` until someone goes to use the collection, which could avoid unnecessary loads from the database.

<TL;DR>
In case you're wondering why I go to the trouble of implementing `ModelsDecorator` (which inherits from `Draper::CollectionDecorator`, as opposed to just using `Draper::CollectionDecorator`, I want the ability to add helpers to the collection itself.  For instance, the helper that renders a link for "New Model" needs to be able to render even if there are no objects in the list.  That helper in turn needs access to context information (i.e. `current_user`) in order to determine whether the user in question has the privileges to create a new object so that it will return an empty string if the user doesn't have the privileges.  So I can't make that helper a class method of `ModelDecorator` - it has to be an instance method of either `ModelDecorator` or `ModelsDecorator` in order to have access to `context`, and since there might not be any objects before someone creates one, the logical place to put it is in `ModelsDecorator`.

**Comment by hayesgm** [comment]
Also, for working with `will_paginate` and `active_admin`, I've used the following:

```ruby
Draper::CollectionDecorator.send(:delegate, :per_page_kaminari)
```

**Comment by danielricecodes** [comment]
The easiest thing to do by far is this:

```ruby
  paginate(@decorated_collection.object)
```

Sure putting all of this in a big project might be a pain, but this doesn't require a lot of effort to implement in simpler applications.
