### ISSUE TITLE
Draper::CollectionDecorator#delegate_all

### ISSUE THREAD

**Issue by jfirebaugh** [drapergem/draper#425]
Should `Draper::CollectionDecorator` not `include Draper::AutomaticDelegation`? I expected to be able to use `delegate_all` in my collection decorator, so that I could use any ActiveRecord query methods, but found that it wasn't defined.

**Comment by itkin** [comment]
maybe we should allow to delgate at least the scope ? My use case working with activeadmin where you want to diplay scoped tables of associated model within their parent show view . hence it would be nice to be able to do : 

```ruby
class BlogDecorator < Draper::Decorator
  decorates_associations :posts, :users
end
# ... and in the view 
blog.posts.active
=> post_decortor_instances
```
And not to have to repeat whenever you want to display a scoped collection : 
```ruby
blog.object.posts.active.decorate(with: PostDecorator)
```
