### ISSUE TITLE
Weird reuse of view context in tests

### ISSUE THREAD

**Issue by schnittchen** [drapergem/draper#580]
Hello,

I've had a bunch of weird ci failures after moving from a osx box to an ubuntu ci box (and a slightly different 1.9.3 ruby version is running on the new box).

The initial symptom was a missing method exception when accessing a helper method. That method should be found implemented in ApplicationHelper (and indeed it is on the old ci machine and my local dev machine).

I had to insert debugging code into the ci runs to get an idea of what was happening...

```
helpers.instance_variable_get(:@view_context).instance_variable_get(:@_controller).inspect
```

revealed that there is a Devise::Mailer still lying around from a previous test, which of course misses ApplicationHelper methods. I put `RequestStore.clear!` in an rspec `before(:each)` as a workaround, which solved the problem. Phew.

I should give some background:
The tests in question were model tests (effectively :type => :model I think), the models being self-rolled view models, misusing Draper to obtain a view context proxy like this:

```
  def helpers
    @helpers ||= Draper::Decorator.new(nil).helpers
  end
```

(I hope this doesn't hurt anyone's feelings... I'm not using Draper as a decorator, but let it do exactly the complicated magic I need here.)

I have no idea why the new ci environment changed behaviour here.

**Comment by jcasimir** [comment]
Sounds like it was annoying, sorry. If the problem persists please sketch out a PR.
