### ISSUE TITLE
decorates_association add a :fill option to fill collection with blank objects up to given size

### ISSUE THREAD

**Issue by mschuerig** [drapergem/draper#582]
I would like to write a decorator like this

```
class DocumentDecorator < ApplicationDecorator
  decorates_association :attachments, fill: 5
end
```

and then use it in a view like this

```
<%= form_for :document do |f| %>
  ...
  <%= f.fields_for :attachments do |af| %>
    <% if af.object.persisted? %>
      ...
    <% else %>
      ...
    <% end %>
  <% end %>
<% end %>
```

For collections, form_for renders its block for each item and takes care of appropriately indexed field names.

In the example, I want to display a fixed number of slots for attachments, some of them maybe empty. For empty slots, I need new, unsaved items to render them.

The view code, as shown above, does not need to know about the number of slots nor does it know how to create a new items. For now, I'm writing the necessary code by hand

```
class ArticleDecorator < ApplicationDecorator
  def attachments
    AttachmentDecorator.decorate_collection(
      fill_empty_slots(
        object.attachments,
        object.max_attachment_count,
        Attachment)
    )
  end
end

class ApplicationDecorator < Draper::Decorator
  protected
  def fill_empty_slots(items, max, klass)
    empty_slots = max - items.size
    blanks = empty_slots.times.map { klass.new }
    items + blanks
  end
end
```

I'm hoping that Draper could handle this for me.

**Comment by jcasimir** [comment]
Sorry, doesn't seem relevant. Feel free to experiment with an implementation and send a PR though.
