### ISSUE TITLE
Put generated methods in an includeded module to facilitate overriding

### ISSUE THREAD

**Issue by mschuerig** [drapergem/draper#583]
Methods defined by "macros" such as decorates_assigned and decorates_association should not add instance methods directly to the enclosing class. Instead, they ought to define those methods within a module that is included in the enclosing class.

Currently, with generated methods defined in the class itself, in order to override such a method one has to resort to alias_method_chain or similar.

With the generated methods defined in a module, it is easier an cleaner to override them and still refer to the generated implementation using super.

**Comment by jcasimir** [comment]
Good idea, please submit a PR.
