### ISSUE TITLE
decorator_class? uses exception

### ISSUE THREAD

**Issue by kenn** [drapergem/draper#586]
In decoratable.rb:

```ruby
def decorator_class?
  decorator_class
rescue Draper::UninferrableDecoratorError
  false
end
```

This code can get significantly slow, particularly when called repetitively on a large collection. Generally begin-rescue is 20 times slower than if-then conditionals.

It would be great if there's more straightforward way to check the existence of a decorator definition.

**Comment by jcasimir** [comment]
I want to remove the idea of inferring decorators, so "won't fix".
