### ISSUE TITLE
Decoration of namespaced models

### ISSUE THREAD

**Issue by commel** [drapergem/draper#587]
I am using the Version-model of PaperClip (https://github.com/thoughtbot/paperclip) to show historifed data. Loving the decoration draper-gem I want to use it as well. :-) 

Everything worked fine, except till the moment when PaperClip decided to move the Version-Model-Class to a Namespace. Now I have to access PaperClip::Version.

How do I tell Draper this?? He keeps missing the model

```
Draper::UninferrableDecoratorError (Could not infer a decorator for PaperTrail::Version.):
  app/controllers/welcome_controller.rb:18:in `decorate'
  app/controllers/welcome_controller.rb:7:in `index'
```

**Comment by jcasimir** [comment]
Going to remove the idea of automatic inference, so closing this issue.
