### ISSUE TITLE
decorates_assigned only for specified actions

### ISSUE THREAD

**Issue by dhampik** [drapergem/draper#594]
Example says, that we can specify ```decorates_assigned :article```. But this will create ```article``` method for all actions, even for those, that do not have ```article``` instance variable defined.

Maybe it's possible to add ```:only``` and ```:except``` options to specify the list of actions for which the rule is applied to?
I mean something like ```decorates_assigned :article, only: [:show, :update]``` or ```decorates_assigned :article, except: [:index]``` This will allow us to avoid phantom instance variables and methods to be generated. Please, correct me if I'm wrong.

**Comment by jcasimir** [comment]
Sounds great, please send a PR.
