### ISSUE TITLE
Draper view context not set up in prepend_before_filters.

### ISSUE THREAD

**Issue by matthewtuck** [drapergem/draper#604]
In our app we had a subtle problem that turned out to be due to a timing issue with the following draper code in ````lib/draper.rb````:

    before_filter do |controller|
      Draper::ViewContext.clear!
      Draper::ViewContext.controller = controller
    end

As such any prepend_before_filter calling through to draper can crash by not being set up.

Our app uses Devise on Rails 3.2, and this can happen due to the following chain:
prepend_before_filter :require_no_authentication ->
ApplicationController#after_sign_in_path_for ->
decorator ->
routing helper

This then fails because request is nil. Here's the relevant stacktrace excerpt (app details replaced):

NoMethodError: undefined method `host' for nil:NilClass
    /gems/actionpack-3.2.16/lib/action_controller/metal/url_for.rb:30 in "url_options"
    /gems/actionpack-3.2.16/lib/action_view/helpers/url_helper.rb:37 in "url_options"
    /gems/actionpack-3.2.16/lib/action_dispatch/routing/url_for.rb:148 in "url_for"
    /gems/actionpack-3.2.16/lib/action_view/helpers/url_helper.rb:107 in "url_for"
    /gems/actionpack-3.2.16/lib/action_dispatch/routing/route_set.rb:216 in "my_route_path"
    /gems/draper-1.3.0/lib/draper/helper_proxy.rb:29 in "block in define_proxy"
    /app/decorators/my_decorator.rb:161 in "my_method"
    /app/controllers/application_controller.rb:81 in "after_sign_in_path_for"
    /gems/devise-1.5.4/lib/devise/controllers/internal_helpers.rb:100 in "require_no_authentication"
    /gems/activesupport-3.2.16/lib/active_support/callbacks.rb:407 in "_run__4458806920851191262__process_action__3853856683597032565__callbacks"

Not sure how you might fix this, because changing to a ````prepend_before_filter```` will result in reverse order and you'll still be too late. But I can say this is a regression we saw by upgrading from 0.18.0 to 1.3.0.

The workaround we have applied is to temporarily hack this by assigning the context manually in our ````after_sign_in_path_for````method.

Sorry, no test app available, but I'll try to respond quickly to any questions.

**Comment by webit-dev** [comment]
We have exactly that problem and tried to use draper 1.4, but it does not fix it.
We use rails 4.1.9 and devise 3.2.4 if that matters.

Problem is still there!

**Comment by jcasimir** [comment]
Sorry, I don't think we know how to fix this.
