### ISSUE TITLE
Decorated models break some find_by queries

### ISSUE THREAD

**Issue by markturner** [drapergem/draper#606]
For example:

<code>Message.find_by(recipient: user)</code> works, whereas <code>Message.find_by(recipient: user.decorate)</code> causes an error: 

<code>PG::UndefinedColumn: ERROR:  column message_receipts.recipient does not exist</code>

The actual column name is recipient_id of course, and changing the query to search by <code>recipient_id</code> and passing <code>user.id</code> does work when user is decorated.

It would be good if you could use the more pleasing syntax supported by AR though.

**Comment by jcasimir** [comment]
Please sketch out a PR, thanks!
