### ISSUE TITLE
Draper adds an empty record to associated collection when rendering.

### ISSUE THREAD

**Issue by firedev** [drapergem/draper#609]
I have a piece of code similar to the following:

```
# controller

@model = Model.find(params[:id]).decorate
@model_comments = @model.comments
```
```
# view

render partial: 'model_comment', collection: @model_comments, as: :comment 
```

The problem is, It always adds and empty `Comment` with all fields set to `nil` at the end.

I have fixed it like this for now:

```
# controller

@model = Model.find(params[:id]).decorate
@model_comments = Model.find(params[:id]).comments
```

What is interesting, `@model_comments.count` is correct. But even when I try to render comments in cycle an additional empty `Comment` appears anyway:

```
# view

@model_comments.each do |comment|
  render 'model_comment', comment: comment 
end
```

Rails 4.0.4

**Comment by jcasimir** [comment]
Closing for age.
