### ISSUE TITLE
Can't use #html_safe inside collection decorators (?)

### ISSUE THREAD

**Issue by nicooga** [drapergem/draper#612]
I have the following

~~~ruby
class ThreadDecorator < Draper::Decorator
  delegate_all
  decorates_association :tags
  # bla bla...
end

class TagsDecorator < Draper::CollectionDecorator
  def to_s
    decorated_collection.map do |tag|
      h.content_tag(:span, tag.name, class: 'label label-info')
    end.join(' ')
  end
end
~~~
The 'issue' is that appending `.html_safe` at the end of `TagsDecorator#to_s` won't escape the result, so I have to put `decorated_thread.tags.to_s.html_safe.` which looks a little bit akward in the views.

Not a life or death issue, but does this something to do with draper?

**Comment by jcasimir** [comment]
Please reopen if you have any new info.
