### ISSUE TITLE
Generator fails when using Minitest::Rails - minitest not found

### ISSUE THREAD

**Issue by chriskottom** [drapergem/draper#615]
I get an error when attempting to generate a decorator:

``` bash
ck1@ramanujan:~/Projects/myapp/$ rails g decorator foo
      create  app/decorators/foo_decorator.rb
       error  minitest [not found]
```

Version information:
- rails - 4.1.0
- draper - 1.3.0
- minitest-rails - 2.0.0.beta1
- minitest - 5.3.3

**Comment by lgs** [comment]
works for me too like @incorvia (thanks), 
... by moving 'minitest-rails-capybara' into my "test, development'.

**Comment by danielpclark** [comment]
:+1:  @incorvia

**Comment by darmenise** [comment]
For Rails 5 the fix is to remove this line:

```ruby
config.generators do |g|
 g.test_framework :minitest # <= it is not needed anymore
end
```
