### ISSUE TITLE
Support for `active_attr` models?

### ISSUE THREAD

**Issue by jdickey** [drapergem/draper#619]
Chris Griego's [`active_attr` Gem](https://github.com/cgriego/active_attr) is getting attention as a generally nice way to "create plain old ruby models with functionality found in ORMs, like ActiveRecord, without reinventing the wheel." I've been using it for a couple of projects, as have many others. There's even a [Railscasts episode](http://railscasts.com/episodes/326-activeattr) covering it.

Draper exhibits some, erm, "quirks" when asked to decorate an `active_attr` model.

Given this model:

```ruby

class Person
  include ActiveAttr::BasicModel
end

```

and this decorator class

```ruby
class PersonDecorator < Draper::Decorator
  delegate_all

  def quux
    'quux'
  end
end
```

this *does not* work:

```
pry(#<RSpec::Core::ExampleGroup::Nested_1>)> z = Person.new.decorate
NoMethodError: undefined method `decorate' for #<Blog::Person:0x007f9c6b8714a0>
from (pry):53:in `block (2 levels) in <module:Blog>'
```

but this does:

```
[27] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> z = Person.new
=> #<Blog::Person:0x007f9c6b8c1180>
[28] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> z = PersonDecorator.decorate z
=> #<Blog::PersonDecorator:0x007f9c6b951e88
 @context={},
 @object=%<64a056e0Blog::Person:0x007f9c6b8c1180>>
[29] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> z.quux
=> "quux"
```

Any ideas?

* Draper 1.3.0
* Ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-darwin12.5.0]
* rbenv 0.4.0-97-gfe0b243
* Rails 3.2.18
* RSpec 2.14.8
* Pry 0.9.12.6

**Comment by jcasimir** [comment]
Going to remove `.decorate`, so "won't fix" for now.
