### ISSUE TITLE
State of this gem

### ISSUE THREAD

**Issue by dmitry** [drapergem/draper#621]
What is the state of this gem? Is there are still anyone supporting it?

**Comment by asiniy** [comment]
@joelparkerhenderson my draper work for 4.2

**Comment by ywen** [comment]
I would like to contribute if needed

**Comment by marshall-lee** [comment]
Me would like to contribute too :elephant:

**Comment by thontaddeo** [comment]
I would also be interested in helping out if it's needed !

**Comment by leo2808** [comment]
is there any way to access wrapped class  from decorator class?

**Comment by gustavokloh** [comment]
I would like to maintain part-time. Maybe helping an official maintainer.

**Comment by dmitry** [comment]
If you would like to be a maintainer or help to maintain, just start doing that by looking through issues and PRs.

**Comment by emaiax** [comment]
I'd like to contribute as well. :)

**Comment by marshall-lee** [comment]
There are already a *lot* of PRs and nobody cares :(

**Comment by dmitry** [comment]
@marshall-lee can you suggest an examples?

**Comment by lucianosousa** [comment]
@jcasimir should we put back the PR #647 again?

**Comment by codebycliff** [comment]
For anyone coming across this, there will be a release of Draper very soon with support for Rails 5 and 5.1. I have made it through the majority of open pull requests and am working through the issues as we speak. I plan to continue to maintain the gem going forward.
