### ISSUE TITLE
Decorating Null Objects

### ISSUE THREAD

**Issue by mauriciopasquier** [drapergem/draper#627]
Lately I've changed how I decorate associations from this:

    decorates_association :something

to this:

    def something
      SomethingDecorator.new object.try(:something)
    end

So I can use decorators as Null Objects in the view.

I wanted to ask if there were "best practices" related to this pattern, some design
problem I can't see with this approach or even if there was interest in an option like `decorates_association
:something, null_object: true`, but then I found [this
commit](https://github.com/drapergem/draper/commit/f0a164) which implies some kind of issue with this usage.

Any thoughts about it? Thanks!

**Comment by jcasimir** [comment]
Seems just fine to me!
