### ISSUE TITLE
uninitialized constant ActionDispatch::RequestId on Rails 3.0.9

### ISSUE THREAD

**Issue by edipofederle** [drapergem/draper#635]
Hi, I am trying use this gem on my rails 3.0.9 rails project and a get this error:

``
/Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/request_store-1.0.7/lib/request_store/railtie.rb:4:in `block in <class:Railtie>': uninitialized constant ActionDispatch::RequestId (NameError)
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `instance_exec'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `run'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/initializable.rb:50:in `block in run_initializers'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `each'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `run_initializers'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/application.rb:134:in `initialize!'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/application.rb:77:in `method_missing'
	from /Users/elf/tougg/orders/config/environment.rb:8:in `<top (required)>'
	from /Users/elf/tougg/orders/config.ru:3:in `block in <main>'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.2.8/lib/rack/builder.rb:46:in `instance_eval'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.2.8/lib/rack/builder.rb:46:in `initialize'
	from /Users/elf/tougg/orders/config.ru:1:in `new'
	from /Users/elf/tougg/orders/config.ru:1:in `<main>'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.2.8/lib/rack/builder.rb:35:in `eval'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.2.8/lib/rack/builder.rb:35:in `parse_file'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.2.8/lib/rack/server.rb:162:in `app'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.2.8/lib/rack/server.rb:253:in `wrapped_app'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.2.8/lib/rack/server.rb:204:in `start'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/commands/server.rb:65:in `start'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/commands.rb:30:in `block in <top (required)>'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/commands.rb:27:in `tap'
	from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/railties-3.0.9/lib/rails/commands.rb:27:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'```

**Comment by jcasimir** [comment]
Sorry, not supporting Rails 3.X.
