### ISSUE TITLE
Hiding Draper inside the model and lazily decorate it

### ISSUE THREAD

**Issue by firedev** [drapergem/draper#636]
Hi,

After using Draper for a while my project became a mess. 

Code smells: `.decorate` everywhere, `decorates_finders`, `delegate_all`, `decorates_association`, `delegate :current_page, :total_pages, :limit_value, to: :source`, ` .dom_id`, `.haml_id` etc. 

So I made this [Decorated](https://gist.github.com/firedev/7a82059b30a2157d4c56) concern that puts decorator inside the model, doesn't pollute its' class so `dom_id` and other things relying on class name can be used as they were before adding Draper. Now the model is lazily decorated model on the first call so you don't need to worry about it.

I suggest to include it in Draper, please let me know what you think.

**Comment by jcasimir** [comment]
I agree on hating `.decorate` but, ethically, I don't think a model should know about the decorator.
