### ISSUE TITLE
Association/parent context not passed deep enough.

### ISSUE THREAD

**Issue by plukevdh** [drapergem/draper#638]
I have a possibly unique use-case that I'd be interested on some feedback on the usefulness of as a general purpose change.

I have a parent object that does `decorates_association` on a child object that requires knowledge of the parent context. Code is a better explainer:

```ruby
# the parent
class CourseDecorator < Draper::Decorator
  delegate :completed_for?
  decorates_association :enrollees, with: UserDecorator
end

# the desired associated method
class UserDecorator < Draper::Decorator
  def completed_course?
    # there is as of yet, no concept of `owner` here, just as an example
    owner.completed_for?(model)
  end
end
```

In most use cases, and if this were server-side only, I could allow `completed_course?` to take an argument of course and pass in the course somewhere in the view. I have two problems with this approach:

1. The user should _already know_ which course we are talking about in context of the association created via the `CourseDecorator`. And in fact, this relationship is carried through to a point (see `owner`: https://github.com/drapergem/draper/blob/master/lib/draper/decorated_association.rb#L8). It just doesn't get propagated to the actual decorated object.

2. I use the decorator in a more generic way to render the object into a flat json blob for client-side rendering as well, during which I do not have a clean means of passing a course to each method on the decorator that depends on understanding the parent context. For example, if I were to have course passed in as an option, it would make the following difficult:

```ruby
  def completed_course?(course)
    course.completed_for?(model)
  end

  def as_json(options={})
    # this won't work because `completed_course?` takes an argument...
    super options.merge({methods: :completed_course?})
  end
```

The current solution is to override the initializer like so:

```ruby
    def initialize(object, options={})
      super
      context[:course] = self
    end
```

which then allows me to use the context like so:

```ruby
  def course
    context[:course]
  end

  def completed_course?
    course.completed_for?(model)
  end

  def as_json(options={})
    # now this works fine
    super options.merge({methods: :completed_course?})
  end
```

While this works, the idea of ownership already exists in the current implementation of Draper, it is simply not passed far enough down to the decorated instances. I think it would take minimal modification to allow the associated decorations to know the context of the decorating object. I have created some small changes that allow for this as an example, though I am not a huge fan of how I accomplished this: https://github.com/plukevdh/draper/compare/owner-context-for-associations

I would appreciate consideration of and feedback on this idea. Thanks.

**Comment by jcasimir** [comment]
I think it's pretty fringe, "won't fix" for now.
