### ISSUE TITLE
The way view contexts are setup during tests hides problems caused by using Draper outside of ActionView

### ISSUE THREAD

**Issue by BRMatt** [drapergem/draper#640]
Using Rails 4.1.6, Draper 1.4.0.

Context: We allow our users to use their own custom email templates on their site, using Liquid. To keep things simple and avoid clashes with Rails' view caching we explicitly render these templates outside the context of ActionView.

When using Draper outside of the context of Rails' built in view rendering (e.g. generating templates with liquid) the library creates a view context using a generic [`ApplicationController`](https://github.com/drapergem/draper/blob/ff41f17fa3789e04c96d8bc2e53de55714e216ab/lib/draper/view_context/build_strategy.rb#L40-L42) instance. This instance will have no request object assigned to its `#request` accessor, but will have all Rails' route/URL helpers included. Trying to call one of the URL helpers will cause [`ActionController::Metal#url_for`](https://github.com/rails/rails/blob/v4.1.6/actionpack/lib/action_controller/metal/url_for.rb
) to be called, which assumes that the `#request` accessor points to a valid request object (which it doesn't).

This causes a `NoMethodError: undefined method 'host' for nil:NilClass` error to be raised.

This mistake is hard to catch during testing because by default Draper will [auto-assign a dummy request to the view context's controller](https://github.com/drapergem/draper/blob/ff41f17fa3789e04c96d8bc2e53de55714e216ab/lib/draper/view_context/build_strategy.rb#L40-L42).

I've found the following temporary workaround for making Draper more closer to how it does in a real mailer that doesn't use Rails' email rendering:

```ruby
before do
  Draper::ViewContext.test_strategy(:full)
  Draper::ViewContext.build!
  Draper::ViewContext.current.controller.request = nil
end
```

And to work around this issue in production you can explicitly give Draper the ActionMailer's view_context:

```ruby
def mail(*args)
  Draper::ViewContext.current = view_context
  super
end
```

Obviously this error is brought on by working around Rails' conventions, but it's frustrating that Draper hides this problem in test environments by default. Is there some way we could change the `ViewContext` builder to not blindly auto-assign requests to view contexts?

**EDIT:** Made it more clear that this is happening because we're not following Rails' conventions exactly.

**Comment by jcasimir** [comment]
The view_context hackery is painful, for sure. Please sketch out a PR if you have ideas.

**Comment by bf4** [comment]
I posted a fix in https://github.com/drapergem/draper/issues/721
