### ISSUE TITLE
Optional arguments not accepted when defining a draper that accepts multiple arguments

### ISSUE THREAD

**Issue by snoblenet** [drapergem/draper#641]
Draper is OK with:

````
class ReviewDecorator < Draper::Decorator
  delegate_all
  def foo(a)
    return "bar"
  end
end
```

...and...

````
class ReviewDecorator < Draper::Decorator
  delegate_all
  def foo(*a)
    return "bar"
  end
end
````

...and...

````
class ReviewDecorator < Draper::Decorator
  delegate_all
  def foo(a, b)
    return "bar"
  end
end
````

However, as soon as I try:

````
class ReviewDecorator < Draper::Decorator
  delegate_all
  def foo(*a, *b)
    return "bar"
  end
end
````

...or...

```
class ReviewDecorator < Draper::Decorator
  delegate_all
  def foo(a, *b)
    return "bar"
  end
end
````

I get a `syntax error, unexpected keyword_end, expecting end-of-input` error.

Why?

Thanks.

**Comment by jcasimir** [comment]
I think it's a Ruby issue, not a Draper issue.
