### ISSUE TITLE
Support dynamic `decorates_assigned`

### ISSUE THREAD

**Issue by Undistraction** [drapergem/draper#643]
It would be great to be able to pass a Proc to `decorates_assigned` to enable dynamic assignment of the decorator based on the model.

For example I have a `PagesController` in which it makes sense to wrap each different page in different Decorator. Currently I have to do this with a method call before render, but would be great to be able to pass a Proc that decides the Decorator type (AboutPageDecorator, HomePageDecorator etc) based on the requested page.

**Comment by jcasimir** [comment]
Sounds interesting, please sketch out a PR.
