### ISSUE TITLE
draper doesn't work with ActiveModelSerializer 0.9.3

### ISSUE THREAD

**Issue by tricknotes** [drapergem/draper#644]
I caught the following error:

```
/Users/tricknotes/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/draper-1.4.0/lib/draper/railtie.rb:48:in `block (2 levels) in <class:Railtie>': uninitialized constant ActiveModel::ArraySerializerSupport (NameError)
```

see: https://github.com/drapergem/draper/blob/v1.4.0/lib/draper/railtie.rb#L48

Work versions:
* AMS 0.8.x: It has `ActiveModel::ArraySerializerSupport`
* AMS 0.9.0: It has no `ActiveModel::ArraySerializerSupport`. But it doesn't run load hooks - so it works.

Doesn't work version:
* AMS 0.9.1: It has no `ActiveModel::ArraySerializerSupport`. And run load hooks - so it doesn't work.

**Comment by jasonayre** [comment]
@tricknotes Are you saying Draper is working for you with 9.2 version of AMS? Because I am getting this same error with 9.2

**Comment by sethherr** [comment]
Me too :+1:

**Comment by savroff** [comment]
Last working version is 9.0.0

**Comment by KurtRMueller** [comment]
Receiving the same error.

**Comment by savroff** [comment]
@KurtRMueller on version ```0.9.0``` you still have error?

**Comment by KurtRMueller** [comment]
Hey @savroff, after reverting back to 0.9.0, I no longer receive the error.

**Comment by stevenharman** [comment]
I have addressed this in #596, which I'm going to rebase atop the latest master and hopefully we can get it merged.

**Comment by lucascaton** [comment]
Hi there. Any news on this one? Thanks.

**Comment by iRet** [comment]
Same error on `0.9.3` :squirrel:

**Comment by nirnaeth** [comment]
we are having this error with `0.9.3`, too. but for other colleagues that have `0.9.0` it works perfectly fine.

**Comment by arpitadhundia** [comment]
@nirnaeth We have the same issue that we discovered during Rails4.2 upgrade. 0.9.3 gives this error, while 0.9.0 does not. Though 0.9.0 has another big bug - #746, which is affecting us now. Any idea when will a fix for this issue be released? So that we can have a gem which has both these bugs fixed?

**Comment by lucascaton** [comment]
Hi @drapergem, any news on this one? Thanks.

**Comment by tboyko** [comment]
+1

**Comment by bigardone** [comment]
+1

**Comment by themire** [comment]
+1

**Comment by fzf** [comment]
+1

**Comment by deefour** [comment]
I'll jump on board too. :+1: I currently use @stevenharman's branch.

**Comment by ExReanimator** [comment]
+1

**Comment by kmarshall008** [comment]
+1

**Comment by atipugin** [comment]
+1

**Comment by mr-dxdy** [comment]
+1

**Comment by apecherin** [comment]
+1

**Comment by rossettistone** [comment]
+1

**Comment by tboyko** [comment]
Pull request patch fixes the issue for me.

+1

**Comment by jcasimir** [comment]
Please try 2.0 and reopen if the problem pops up again.

**Comment by deefour** [comment]
:heart: thank you @jcasimir

**Comment by tricknotes** [comment]
It works fine for me. Thanks :whale:

**Comment by jcasimir** [comment]
Sweet!

**Comment by kmarshall008** [comment]
This is going to be so helpful for us... I'm so glad we trusted you'd get
this sorted and worked on some other items the past few weeks. Thanks for
getting this all figured out so quickly.
