### ISSUE TITLE
Decorating AR model changes 'dup' behavior

### ISSUE THREAD

**Issue by joekur** [drapergem/draper#648]
Happened upon this unexpected interaction with AR when tracking down a bug. I found that while normally calling `dup` on an ActiveRecord model gives you a copy with a nil id, calling it on a decorated model keeps the original id. You can see how this would cause you to overwrite an existing row when you thought you were creating a new one.

I'm not sure if this is a bug or a limitation of how rails overrides dup. I also now realize that I should probably keep decorated models out of my business logic, but it's something that can be easily forgotten, especially if you're reusing controller-level query methods that do the decoration for you.

**Comment by jcasimir** [comment]
Yeah, you're duping the decorator not the underlying model, so the behavior isn't the same.

**Comment by batamire** [comment]
This just caused my app to crash generating 293k records in db.
#dup should delegate to the underlying AR model and redecorate it.
