### ISSUE TITLE
Unknown key: :with. Valid keys are: :context

### ISSUE THREAD

**Issue by krainboltgreene** [drapergem/draper#650]
I think I tracked it down to here: https://github.com/drapergem/draper/blob/master/lib/draper/decorator.rb#L145

**Comment by VarunBatraIT** [comment]
Do you have plural and singular decorators both? If so remove the plural ones (Considering that controllers are plural, models are singular and decorators are singulars :) )

**Comment by jcasimir** [comment]
Can you give more context to what you were doing? Sample app/code?

**Comment by jmaddi** [comment]
I got that error when I accidentally created a plural decorator as an ordinary `Draper::Decorator`, and not as a `Draper::CollectionDecorator`.
