### ISSUE TITLE
Undefined Method error returned on has_many association

### ISSUE THREAD

**Issue by HermannHH** [drapergem/draper#654]
I have various associated model in my application. I have setup Draper to decorate associations upon initialization of the parent class.

I have the following classes:

    Customer (has_many :accounts)
    Account  (belongs_to :customer && has_many :facilities && has_one :contact)
    Contact  (belongs_to :account)
    Facility (belongs_to :account)

I initiate a decorator as follows:

    @customer = Customer.find_by(:token => params[:token]).decorate

In my account_decorator the following is added:

    decorates_association :contact
    decorates_association :facilities

...and in my Customer Decorator I have:

    decorates_association :accounts

The issue I'm experiencing is that an undefined method exception is thrown as soon as I uncomment the "decorates_association :facilities" line above. The decorator works perfectly fine with the Contact model. 

I have double-checked my association mappings as well as my table attribute names. So relatively sure it's not that.

I am running Draper 1.4.0 and Rails 4.1.4

Am I missing anything?

**Comment by jcasimir** [comment]
Please try 2.0 and reopen if still and issue.
