### ISSUE TITLE
Decorator is unable to access helper methods after sending an ActionMailer email.

### ISSUE THREAD

**Issue by notalex** [drapergem/draper#655]
When a helper method is called inside a decorator after sending an email, it throws an error stating that the helper method is not defined.

``` ruby
>> UserMailer.send_email.deliver
>> User.new.decorate.h.current_user
NoMethodError: undefined method `current_user' for #<#<Class:0x00000004c34ef8>:0x00000004c43570>
        from ...gems/draper-1.4.0/lib/draper/helper_proxy.rb:29:in `block in define_proxy'
        from (irb):3
        from ...gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
```

I tried debugging this to no avail. Draper does not seem to have any association with ActionMailer.

I have created a sample app which reproduces this error:
https://github.com/notalex/draper-mailer-error

Any help would be appreciated.

**Comment by tycooon** [comment]
+1, I checked the code and it seems like each time any mailer calls `view_context` method, Draper switches it's global view_context to that mailer's one, which is kind of surprising behaviour.

**Comment by notalex** [comment]
@tycooon, good finding. The bug makes sense now.

**Comment by lebedev-yury** [comment]
+1

**Comment by nurey** [comment]
+1

**Comment by lcoq** [comment]
+1 (tested with Draper 1.3.1)

**Comment by gdurelle** [comment]
Maybe the problem is you shouldn't call a decorator and a mailer in the same portion of code...
Mailers are called from controllers or workers mostly, decorators from views... 
Shouldn't have anything to do together.

**Comment by lcoq** [comment]
@gdurelle you said

> Mailers are called from controllers or workers mostly, decorators from views... 

I would have tell decorators are (mostly) *instantiated* in controllers but *used* in views, so controller stuff has something to do with controller stuff, isn't it ?

**Comment by arjes** [comment]
I was able to work around this by un-monkey patching the view_context method for mailers

``` ruby
  def view_context
    view_context_class.new(view_renderer, view_assigns, self)
  end
```

The monkey patching is occurring here:
https://github.com/drapergem/draper/blob/master/lib/draper/view_context.rb#L8

Check the original function definition against your version of rails.

**Comment by sebabouche** [comment]
:+1:

**Comment by milankubin** [comment]
calling Draper::ViewContext.clear! right after actionmailer is called fixed this for me.
This caused me a lot of headache. Suggesting to put it in the Readme :)

**Comment by milankubin** [comment]
@gdurelle I don't agree
 Best practices for mailing,  (exp with volume and concurrency), to ensure the possibility of delayed mailing, is pass an ID to ActionMailer methods and instantiate objects inside the AM method.  

Following example will have helpers inside the decorator fail:

````ruby
class LeadMailer < ActionMailer::Base
 def client_comments_received(mail_params, lead_id, message_id)
    @lead = Lead.find(lead_id)
    @message  = Message.find(message_id)
    
    @organization = @lead.organization
    @original_message_html = @message.decorate.as_responded_to_html
  end
end
````

this will return a NoMethodError on any helper methods being called inside the decorator (with h. )
````
2016-02-23T16:28:16.260551+00:00 app[web.1]: NoMethodError (undefined method `decode_html' for #<#<Class:0x007f84d6161108>:0x007f84d56be200>):
2016-02-23T16:28:16.260553+00:00 app[web.1]:   app/decorators/message_decorator.rb:38:in `as_responded_to_html'
`````

How would this be addressed?

**Comment by tibbon** [comment]
I'm still experiencing this. I see it was added to the 3.0.0 milestone, but 3.0.1 is out. Bump?

**Comment by milankubin** [comment]
@tibbon Did my proposed workaround helped you at all?

>  calling Draper::ViewContext.clear! right after actionmailer is called fixed this for me.
This caused me a lot of headache. Suggesting to put it in the Readme :)

**Comment by tibbon** [comment]
@milankubin Yep, that's what I've got implemented now. Very much in favor either of it getting into the readme as the canonical way of doing this, or having another fix hopefully.

**Comment by pedrofurtado** [comment]
@notalex You could access by this way:
```ruby
User.new.decorate.h.controller.current_user
```

**Comment by kaikuchn** [comment]
In what way was this issue fixed? I'm still experiencing this problem. The view context leaks between tests since sending a mail registers it with request store and then it does not get cleared..?

**Comment by taylorthurlow** [comment]
Yeah, I'm still experiencing this problem as well. @notalex Do you mind reopening this, if possible?

Might be worth tagging @codebycliff, you seem like you are one of the more recently active contributors that could reopen this.

**Comment by gucki** [comment]
@codebycliff The bug is still present in the latest version 4.0.2.
