### ISSUE TITLE
Revamping Draper

### ISSUE THREAD

**Issue by jcasimir** [drapergem/draper#657]
A group of my students and I are working on Draper over the coming weeks. Some of the things on our hitlist:

* Organize and prune existing issues
* Review and merge or close pull requests
* Fix deprecation issues with the RSpec test suite
* Edit the README
* Release a final 1.X version

If we're successful with that, then I want to work on removing things:

* Review/remove support for old Rails versions
* Review/remove support for old/unused Ruby versions/interpreters
* Review/remove support for MongoDB
* Review/remove features that I don't believe are good programming practices (ie: using `.decorate`)
* If possible, create a draper-contrib or small gems like draper-mongodb and draper-inferences so interested persons can continue to work on / use that functionality
* Release a 2.0

I'll post updates as we make progress.

**Comment by lucianosousa** [comment]
I'm happy you guys are working in this again.

I really suggest drop support to Rails 3.x in the next few releases. I almost opened a issue couple weeks ago and now you're back I can offer my cents here!

Welcome back!

**Comment by jcasimir** [comment]
Agreed. Removing support for fringe cases to reduce code size/complexity is
one of my key areas of focus.

**Comment by jcasimir** [comment]
Got CI back to green by making some fixes, hacks, and dropping legacy support. Version 2.0 released.
