### ISSUE TITLE
Using @user.decorate! instead of @user = @user.decorate

### ISSUE THREAD

**Issue by karlingen** [drapergem/draper#658]
Isn't `@user.decorate!` more beautiful than having to redeclare the variable with the same but decorated value `@user = @user.decorate` ?

For example:
```ruby
class UsersController
  before_action :set_user
  
  def show
    @user.decorate!  
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

private

  def set_user
    @user = User.find(params[:id])    
  end
end
```

The reason why I am not decorating the object inside the private method is because it is known to be bad to run anything serious, if not impossible, after you have decorated the object.

**Comment by chrisbouchard** [comment]
I'm not sure that is possible/desirable when `User` and `UserDecorator` are two different classes. Bang methods don't change the underlying object's identity, just its properties.

**Comment by jcasimir** [comment]
I'm going to remove the .decorate functionality anyway, I don't think it's good OOP style.
