### ISSUE TITLE
Generator needs update for Rspec ~> 3.2

### ISSUE THREAD

**Issue by Epigene** [drapergem/draper#668]
I have a User model that I want to decorate, so I started by generating the decorator:
`rails g decorator User`

This created two files:
`/app/decorators/user_decorator.rb`
`/spec/decorators/user_decorator_spec.rb`

user_decorator_spec.rb is populated with this code:

``` ruby
require 'spec_helper'

describe UserDecorator do
end
```

Recent Rspec uses `require 'rails_helper'`. Since I overlooked this difference, the errors had me going in circles for a couple hours.

Perhaps the generator can be smart about this recent development and modify the require line accordingly based on rspec version?

**Comment by ivanovaleksey** [comment]
Seems like this one can be closed.
RSpec generator's template has been updated [here](https://github.com/drapergem/draper/commit/03f969c503ea56d0192ad772c540bf805e28e9e9).
