### ISSUE TITLE
Explicit declaration resulting in `undefined method `primary_key'`

### ISSUE THREAD

**Issue by adsteel** [drapergem/draper#670]
I have a multi-app application, so declaring `.decorate` results in the common `Could not infer a decorator for ActiveRecord::Base. (Draper::UninferrableDecoratorError)`. So I need to explicitly declare the decoration, which is a good thing anyway.

The decorator is in one app. The model is in another (a base app). The decorator cannot be in the same directory as the model, because the model is shared between apps that each have their own decorators. Here's how I get to the error message:

```
# decorate the instance in Namespace::ApplicationController
decorated_model = ModelDecorator.new(Model.find(id))

# try to use the instance in a relationship assignment
other = Other.find(id)
other.association = decorated_model
=> `undefined method `primary_key' for Namespace::ModelDecorator:Class (NoMethodError)`

# explicitly declaring the association_id avoids the error
other = Other.find(id)
other.association_id = decorated_model.id
```

I can't seem to get around this. Any ideas?

**Comment by phocke** [comment]
Hey @adsteel,


Have you managed to fix or find a way around it?
We've run into the same problem and wonder how to fix it.

**Comment by adsteel** [comment]
@phocke I started decorating the moment before I passed the local variable to the view, which allowed me to assign normally with the undecorated record.

e.g.
```ruby
other.association = record
...
render 'template', locals: { record: record.decorate }
```

**Comment by phocke** [comment]
I'll give a try. Thanks for your input @adsteel

**Comment by apolzon** [comment]
I ran into this myself today. I was able to work around it by implementing an ApplicationDecorator (to steal a page from the Rails 5 book) and implementing the primary_key method there (and updating all my decorators to inherit from ApplicationDecorator):

```ruby
class ApplicationDecorator < Draper::Decorator
  def self.primary_key
    object_class.primary_key
  end
end
```

Note that the object_class method, which is implemented by Draper, will not work for non-standard decorator classes unless you explicitly defined the class it decorates via decorates ClassName, ie:
```ruby
class CustomThingDecorator < ThingDecorator
  decorates Thing
end
```

Depending on your use-case, this may be fine for you, but if your decorator is generic as opposed to custom (ie, it can decorate multiple models), this won't work, but this at least gets you part of the way there.

**Comment by codebycliff** [comment]
@adsteel I think your most recent comment is the right solution. Ultimately, objects should be decorated at the last moment before passed to the view.

Is this still a paint for any of you? and if so, is there any reason you can't move to decorating at the end?

**Comment by adsteel** [comment]
@codebycliff this issue inspired me to write my own decorator library, which avoided this sort of pain point. Ultimately that journey led me to realize this sort of decoration pattern wasn't the solution I was looking for. So... no more pain, but I also don't use draper anymore.
