### ISSUE TITLE
I18n human_attribute_name confilct

### ISSUE THREAD

**Issue by JelF** [drapergem/draper#671]
When `human_attribute_name` is called, it checks ancestors of decorated model using this code 

```
    def lookup_ancestors
      self.ancestors.select { |x| x.respond_to?(:model_name) }
    end
```

Then, it calls `#model_name` of all found ancestors including `Draper::Decorator` and crashes

I fixed it by delegating `self.lookup_ancestors` to `object_class` in my `ApplicationDecorator`,  but not sure it is   a good idea

**Comment by codebycliff** [comment]
@JelF Are you still experiencing this issue? If so, can I get more details (e.g. draper version, rails version, stack trace, etc.)? I can't seem to reproduce it at all:

![image](https://cloud.githubusercontent.com/assets/651946/24982069/30b2af9c-1fa5-11e7-8a3e-b220bb619919.png)

**Comment by JelF** [comment]
@codebycliff no more, seems it have been fixed

**Comment by codebycliff** [comment]
Sounds good. I will close it then.
