### ISSUE TITLE
Looping has many relation with <i> tags 

### ISSUE THREAD

**Issue by Stefflan00** [drapergem/draper#686]
Is it possible to loop over multiple i tags?
my model has a has_many relation with Geography so i want to display the flags in the frontend.
So the question is where and how should i do the loop?

```
def geo_to_flags
    h.content_tag :span, title: geographies.map(&:code).join("|") do
      geographies.each do |geo|
       h.content_tag(:i, class: "famfamfam-flag-#{geo.code}") do
       end
      end.joins
    end
  end
```

this is not working

Or is this approach completely wrong?

**Comment by codebycliff** [comment]
This doesn't have anything to do with Draper, but instead with how to write helpers. Something like this should work though:

```ruby
def geo_to_flags
  h.content_tag :span, title: geographies.map(&:code).join('|') do
    geographies.each do |geo|
      h.concat h.content_tag(:i, nil, class: "famfamfam-flag-#{geo.code}")
    end
  end
end
```

There may be a better way to accomplish this, but that will do it.
