### ISSUE TITLE
Draper relies on active_model/serializers/xml which is being removed in Rails 5

### ISSUE THREAD

**Issue by audionerd** [drapergem/draper#697]
If you try using Draper on Rails 5, and you have `spring` enabled, you'll see this less-than-helpful error message:

```bash
./bin/rails:6: warning: previous definition of APP_PATH was here
Usage: rails COMMAND [ARGS]

The most common rails commands are:
 generate    Generate new code (short-cut alias: "g")
 console     Start the Rails console (short-cut alias: "c")
 server      Start the Rails server (short-cut alias: "s")
[...]
```

If you disable `spring`:

```bash
~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/draper-2.1.0/lib/draper.rb:5:
  in `require': cannot load such file -- active_model/serializers/xml (LoadError)
```

In Rails 5, [`active_model/serializers/xml` has been extracted into its own gem](https://github.com/rails/rails/pull/21161). So, a quick solution is to add the `activemodel-serializers-xml` gem to your `Gemfile`:

```ruby
gem 'activemodel-serializers-xml', git: 'https://github.com/rails/activemodel-serializers-xml'
gem 'draper'
```

There is not yet a published release of `activemodel-serializers-xml`, hence the need to retrieve it from `master` in GitHub.

I was able to run Draper on Rails 5 with this solution, although I didn't run any of Draper's tests so I don't yet know what other issues might crop up.

**Comment by jasnow** [comment]
This issue helped me - THANKS !!!

**Comment by olivierlacan** [comment]
Bit shorter solution:

```ruby
gem 'activemodel-serializers-xml', github: 'rails/activemodel-serializers-xml'
gem 'draper'
```

**Comment by seanlinsley** [comment]
#752 has been merged and 3.0.0.pre1 released, which fixes this.

**Comment by tute** [comment]
We are about to publish in rubygems ambry v1, with no XML support (or dependency): https://github.com/norman/ambry/releases/tag/v1.0.0.

Thanks!

**Comment by fcostabr78** [comment]
great!
