### ISSUE TITLE
rails console command fails if using Rails 5

### ISSUE THREAD

**Issue by audionerd** [drapergem/draper#698]
```
[..]rails-172c25e7b62b/actionpack/lib/action_controller/test_case.rb:31:in `initialize': wrong number of arguments (0 for 2) (ArgumentError)
    from [..]draper-2.1.0/lib/draper/view_context/build_strategy.rb:41:in `new'
```

In Rails 5, [`ActionController::TestRequest.new` expects args for env and session](https://github.com/rails/rails/commit/3806eb70a63f0252c88ebb25f0aa79b4c0ca5686), but Draper could be using [`ActionController::TestRequest.create`](https://github.com/rails/rails/commit/78a5124bf09d0cd285d4d1a6242bd67badb2f621) instead, which provides these.

**Comment by arnlen** [comment]
Still happening with Rails `5.0.0.rc1` (tested with `ruby 2.3.1p112`)

**Comment by pavelbulanov** [comment]
Still there? Rails 5.0 stable is now out, so should become more of a priority

**Comment by neves** [comment]
Still not working with Rails 5.0 stable

**Comment by seanlinsley** [comment]
Hi everyone, please give #752 a try.

**Comment by codebycliff** [comment]
This should be fixed in master now.
