### ISSUE TITLE
Is it possible to decorate find_each Enumerator object

### ISSUE THREAD

**Issue by jarosan** [drapergem/draper#703]
Hi,

Is there a way to decorate `Model.find_each` collection? Currently i have to do the decoration in the view.

Cheers.

**Comment by lucianosousa** [comment]
you can do it here.
https://github.com/drapergem/draper#decorating-individual-elements

if you are doing queries in your view, you are wrong.

**Comment by jarosan** [comment]
@lucianosousa i think you misunderstood what i am trying to do.
```
def index
  @places = PlaceDecorator.decorate_collection(Place.find_each(batch_size: 10))
end
```
This doesn't work :disappointed: It loads all places ignoring `batch_size` in `for_each` and then decorates them.

More info on for_each here: http://apidock.com/rails/ActiveRecord/Batches/ClassMethods/find_each

**Comment by lucianosousa** [comment]
I just ran here this find_each method with batch size and it returns all items on my DB, ignoring the batch_size.

It's not a draper problem, seems your query is not right.

**Comment by jarosan** [comment]
That's what i'm saying. It ignores the batch_size. My question was if there was a way to decorate find_each collection in controller while keeping the find_each functionality. Apparently there is no way to do it.
