### ISSUE TITLE
Test classes loaded unecessarily

### ISSUE THREAD

**Issue by drock** [drapergem/draper#704]
This is related to #690 but not the same.

If the Rails.env.test? is true then Draper::Railtie is automatically bringing in draper/test_case.  However, just because the environment is "test" doesn't necessarily mean that we are running tests and need the test cases classes loaded.  This is particularly true with systems such as CircleCi which by default will export RAILS_ENV="test" and then run various rake tasks.

This is particularly a problem with Ruby 2.2 and Rails 3.2.  The inclusion of draper/test_case then brings in active_support/test_case which in turn loads test/unit.  The unbundled test-unit gem installs an at_exit hook to auto run the tests.  Now, we have any rake task trying to auto run a test unit suite and it bombs.

This example is really more of a side effect of the higher level problem which is that the test library is being loaded even if we aren't necessarily running tests.

**Comment by codebycliff** [comment]
I'm running the latest Draper with Rails 5 in CircleCI with no problem. Draper no longer support Rails 3 / test-unit, which appears to be more of the issue. I also think it's a fair assumption that it's okay to load a libraries test classes when the Rails environment is test.
