### ISSUE TITLE
Rails 3.2 and Ruby 1.9.3 support really dropped in 2.0.0

### ISSUE THREAD

**Issue by gamov** [drapergem/draper#709]
I read this in the master change log:
> Rails 3.2 support dropped
> Ruby 1.9.3 and 2.0 support dropped

But bundling my Rails app (3.2/Ruby 1.9.3) works fine. Is it an oversight in the gem spec file or an erroneous change log?

**Comment by KensoDev** [comment]
I am guessing it refers to this commit: https://github.com/drapergem/draper/commit/25d4c843dd776d3779cc77fe2c7e756fe865ab99

gemspec file didn't change so I think you shouldn't have a problem bundling it with those versions

**Comment by gamov** [comment]
@KensoDev good call, thx!
