### ISSUE TITLE
How to stub a decorator on a decorated association?

### ISSUE THREAD

**Issue by samstickland** [drapergem/draper#722]
I have one decorator (let's called it Invoice) that depends on a method from an associated decorator  (let's called it Order)

I don't want my Decorator tests for Invoice to depend on a real Order object, but I can't seem to stub the decorated method in OrderDecorator.

```
class OrderDecorator
  def display_name
     "#{date.strftime('%d/%m/%Y')} / #{name}"
  end
end

class InvoiceDecorator
  delegate_all

  decorates_association :order

  def display_name
    "Invoice #{number} for #{order.display_name}"
  end
end
```

In my tests I don't want to have to instantiate a Order or Invoice to be able to test the decorators, and I don't want the test for InvoiceDecorator#display_name to depend upon the results of OrderDecorator#display_name

So, I tried something like this:

```
order = double(Order, display_name: 'XXXX')
invoice = double(Invoice, number: '12345')

decorator = InvoiceDecorator.new(invoice)
allow(decorator).to receive(:order).and_return(order)

expect(decorator.display_name).to eq "Invoice 12345 for XXXX"
```

But what I see is that the associated decoration is lazy evaluated - i.e. it doesn't try to decorate order until decorator.display_name is called... which gives the following error:

```
Draper::UninferrableDecoratorError:
  Could not infer a decorator for RSpec::Mocks::Double.
```

Fixing that with:

```
decorates_association :order, with: OrderDecorator
```

Gives: 

```
undefined local variable or method `date' for #<OrderDecorator:0x0000000b60bac0>
```

Which means the the stub:

```
allow(decorator).to receive(:order).and_return(order)
```

Did not work... 

Is there a way to make this happen? Or is there a fault with my design?

**Comment by syguer** [comment]
@samstickland 
> Draper::UninferrableDecoratorError:
>   Could not infer a decorator for RSpec::Mocks::Double.

Because Draper try to find Decorator by associate name.
There is a couple ways  to fix problem.

1. Stop to use `double`
It seems to pass your spec after change to following with...
```ruby
order = Order.new(display_name: 'XXXX')
invoice = Invoice.new(number: '12345')
```

If you need mock with method, you can use stub.
```ruby
order = Order.new
allow(order).to receive(:display_name).and_return 'XXXX'
invoice = Invoice.new
allow(order).to receive(:number).and_return '12345'
```

2. Add decorator name specification
```ruby
decorates_association :order, with: OrderDecorator
```

This is your workaround. The error you got seems to fix by adding `delegate_all` to `OrderDecorator`

**Comment by codebycliff** [comment]
@samstickland Both of the above suggestions seem like good solutions to the problem. Ultimately, the class inference isn't terribly great and I can't recommend enough the explicit specification (i.e. `with: OrderDecorator`).
