### ISSUE TITLE
`source` method name conflicts with AR relation

### ISSUE THREAD

**Issue by troex** [drapergem/draper#725]
I have a model:

``` ruby
module Shop
  class Click < ActiveRecord::Base
    belongs_to :source, polymorphic: true
  end
end
```

When model is undecorated calling `click.source` returns AR relation, but if model is decorated it returns self when called. example `click.decorate.source == click` returns `true`

I understand this is internal name conflict, but I couldn't find any info on "reserved" method names. Any luck getting AR relation without changing relation name?

**Comment by troex** [comment]
References #501, solution is provided but old alias methods still present

**Comment by troex** [comment]
```ruby
module Draper
  class Decorator
    remove_method :source
  end
end
```

worked for me as a temporary solution

**Comment by wilkenm** [comment]
Just spent a few hours dealing with this issue, +1 for getting rid of the 'source' alias now that it's not used internally.

**Comment by codebycliff** [comment]
This is in master now.
