### ISSUE TITLE
ApplicationDecorator class

### ISSUE THREAD

**Issue by dmitrypol** [drapergem/draper#727]
A common pattern in Rails is to have ApplicationController, ApplicationMailer, etc.  The class inherits from base and developer generated code inherits from it.  This provides a useful place to implement common functionality.  

We are manually introducing this in our app it but it could be a built-in feature.  Does anyone have ideas / suggestions?  

```
class ApplicationDecorator < Draper::Decorator
  delegate_all
  ...
end
class UserDecorator < ApplicationDecorator
  ...
end
```

**Comment by anbiniyar** [comment]
I did the same thing as well. +1

**Comment by Mehonoshin** [comment]
Nice idea!

**Comment by francirp** [comment]
👍 I do the same thing. I typically implement `currency` and `percent` class methods in my `BaseDecorator`. If you're curious I wrote a post on it here: https://medium.com/@ryan_p_francis/how-decorators-saved-my-rails-app-c5cc18ef7d2e

**Comment by MrEmelianenko** [comment]
Yeap, good idea! We could create rake task `rake draper:install` to create this file automatically.

**Comment by francirp** [comment]
Yeah exactly. Happy to take a first punch at a PR for this if it's something the team wants to pursue. Who makes decisions like this on the Draper team? @seanlinsley what are your thoughts on the subject?

**Comment by seanlinsley** [comment]
👍 sounds like a good idea

**Comment by codebycliff** [comment]
This seems like a good idea. Is anyone still interested in taking a stab at a PR?

**Comment by chuck-john** [comment]
@codebycliff, this is a great idea.  I'll get a branch started.

**Comment by codebycliff** [comment]
This was merged in https://github.com/drapergem/draper/pull/796.
