### ISSUE TITLE
Is there a way to get a Hash from a decorator object?

### ISSUE THREAD

**Issue by kapso** [drapergem/draper#730]
I guess I can always to `JSON.parse(decorator.to_json)` but was trying to avoid this step.

**Comment by ivanovaleksey** [comment]
`Draper::Decorator` includes `ActiveModel::Serialization` so you can try to use `ActiveModel::Serialization#serializable_hash` method.

Assuming you have `Foo` class and `FooDecorator`:
```
decorated = foo.decorate
decorated.serializable_hash
```

**Comment by codebycliff** [comment]
Yes, as mentioned above, you can use `#serializable_hash` to get a Hash from a decorator.
