### ISSUE TITLE
Is this gem abadoned?

### ISSUE THREAD

**Issue by Mehonoshin** [drapergem/draper#735]
Seems that there were no new commits in master for a year.
Does anybody still maintain this gem?
Rails 5 is going to be released soon, and draper is not compatible with it.

**Comment by lucianosousa** [comment]
:+1: 

Yes, if possible make a public call to someone be a new maintainer

**Comment by zlobz** [comment]
Try `Cells` gem
https://github.com/apotonick/cells

**Comment by dreyks** [comment]
cells and draper are not entirely same things

**Comment by lucianosousa** [comment]
makes more sense it: https://github.com/fnando/burgundy

**Comment by weimeng** [comment]
I'm guessing @jcasimir will be the most relevant person to answer this question right now.

**Comment by seanlinsley** [comment]
@steveklabnik recently gave me commit access, specifically in order to get Draper working with Rails 5. I can't speak to how much work I'll do on Draper after that.
