### ISSUE TITLE
Drape - New life for Draper

### ISSUE THREAD

**Issue by MrEmelianenko** [drapergem/draper#742]
Hello,

I'm sorry for advertising. I'm doing this not for PR, I'm doing this for help the people.
I think the fact that this gem is no longer supported, it is a big problem for all of us.

That is why I decided to create [Drape](https://github.com/MrEmelianenko/drape/wiki/Meet-Drape!) - the adapted version of Draper for Ruby on Rails 5 with some fixes.

I would be very grateful for any support and development.

Best Regards,
Andrew

**Comment by seanlinsley** [comment]
@MrEmelianenko I recently gained commit access to Draper specifically in order to get it working with Rails 5. Would you be interested in merging your changes into Draper, and becoming a maintainer?

**Comment by MrEmelianenko** [comment]
@seanlinsley Yes, It would be great. But It will be little difficult, because I'm do not fork the Draper repository, just create new one. Also I removed some outdated code for Rails 3, we need merge it very carefully.

**Comment by MrEmelianenko** [comment]
@seanlinsley What's the next steps? If you want I can prepare the PR at this week.

**Comment by md5** [comment]
@seanlinsley You may want to take a look at the comments for https://github.com/drapergem/draper/issues/681 where there is some discussion about collecting Rails 5-related fixes.

**Comment by md5** [comment]
There's also https://github.com/drapergem/draper/pull/712 and probably others

**Comment by MrEmelianenko** [comment]
@md5 Thank you for your comments! I have already checked it when I created my version of Draper for Rails 5.

**Comment by shaneog** [comment]
Hi @seanlinsley - since you have committer access now, do you recommend to use @MrEmelianenko's [Drape](https://github.com/MrEmelianenko/drape) or wait for a new Draper release?

**Comment by seanlinsley** [comment]
I would suggest continuing to use Draper.

**Comment by shaneog** [comment]
Great! Do you need any help in preparing a Rails 5 release, and if not, do you have an idea when one would be ready? 
Thank you for your work!

**Comment by pavelbulanov** [comment]
See work on rails-5 branch is happening now in the real time. Thanks @seanlinsley

**Comment by seanlinsley** [comment]
I just opened a PR with my changes: https://github.com/drapergem/draper/pull/752. There are still a few things to do, but the tests are passing. Please review the changes and try the branch out in your app.

**Comment by seanlinsley** [comment]
@MrEmelianenko are there things from Drape that you would like to see in Draper? Feel free to create PRs for them!

#752 should now be complete. Once I get Rubygems access from @steveklabnik I'll create a release candidate.

**Comment by seanlinsley** [comment]
3.0.0.pre1 has been released. Please give it a test and open tickets for any issues found.

I'm going to go ahead and close this ticket. @MrEmelianenko I'd be happy to add you as a Draper maintainer 😄

**Comment by MrEmelianenko** [comment]
@seanlinsley It would be great, I think together we can make a lot of great things for Draper.

**Comment by seanlinsley** [comment]
I just invited you :octocat:

**Comment by McRip** [comment]
@MrEmelianenko, @seanlinsley: Is anybody of you still working on Draper or Drape?
