### ISSUE TITLE
Draper doesn't comply with ActiveModel API for collections. 

### ISSUE THREAD

**Issue by HoneyryderChuck** [drapergem/draper#745]
Coming from https://github.com/jeremyevans/sequel/issues/1201#event-685844858

I'm replacing a rails project AR layer with sequel, which uses draper. Although there is no built in support in draper for Sequel (the `.decorate` mixin is not automatically added), It's fairly easy to add it (I'm including `Draper::Decoratable`). 

Using `decorates_assigned` for single record instances works fine. However, when using `decorates_assigned` in the controller for collections out-of-the-box, if breaks. From the naming conventions I have the decorator defined (`CarDecorator` for `@car`, `CarsDecorator` for `@cars`), but this can't be inferred, as the sequel dataset doesn't respond to `.decorate`. After including the same module above, It breaks, as Sequel::Dataset doesn't respond to `#model_name`. 

`#model_name` is a method which belongs to the ActiveModel API, but this is **not** specced for collections. `draper` takes therefore advantage of a method defined for AR association proxies, which is not even under ActiveModel namespace (`ActiveRecord_Associations_CollectionProxy`). 

Now, it's not completely wrong that draper goes out of the boundaries of ActiveModel and provides AR-only support, but then it should state that it **only** fully supports AR and features might break for other ORMs, or comply with the spec and not make things magically work for AR-collections-only. In the end, correcting it was as easy as passing a decorator:

``` ruby
decorates_assigned :cars, with: CarsDecorator
```

which some documentation could have saved me the trouble of.

**Comment by Alexander-Senko** [comment]
Is there any _ActiveModel API for ~collections~_ associations? I believe, not. That's why Draper relies on `ActiveRecord::Associations` for that, I guess.

After reading through both the original issue and this one, it still stands unclear for me what behavior do you expect of Draper in this case. What API should it implement?

Anyway, the issue should be redefined to be further considered.
