### ISSUE TITLE
use delegate_all may call method that not expected

### ISSUE THREAD

**Issue by angelfan** [drapergem/draper#757]
``` ruby
class OrderDecorator < ApplicationDecorator
  delegate_all
end
```

I found when `Object` have instance method `message`
and Order also have instance method `message`
in this condition 
`OrderDecorator` will call `Object#message` instead of  `Order#message`

**Comment by Mohit-Pawar** [comment]
Hi @angelfan, I was not able to reproduce the issue. OrderDecorator called Order#message not Object#message. could you please share ApplicationDecorator code. When your decorator calls delegate_all, any method called on the decorator not defined in the decorator itself will be delegated to the decorated object. I don't think this is an issue
