### ISSUE TITLE
"Reapplying foo decorator to target that is already decorated with it." warning?

### ISSUE THREAD

**Issue by roalcantara** [drapergem/draper#758]
Sorry folks, I've pressed enter accidentally without finish it. 😅

_Environment:_
- Rails 5.0.0
- draper 2.1.0
- activemodel-serializers-xml: rails/activemodel-serializers-xml

First of all, thank you so much for this great gem.

I don't really know if this is a bug. It's definitely a question, tho.

I've installed the gem, followed the installation instructions in the README file, creating the decorator `FooDecorator` class under the `/app/decorators` directory.

In my `FooController`, when I execute:

```
def set_foo
   @foo = Foo.find(params[:id]).decorate
end
```

the decoration is done beautifully. Excellent!

However, on my console, the following warn is thrown: `Reapplying foo decorator to target that is already decorated with it.`

The weird thing is that the object `@foo` hadn't been decorated previously and I don't quite understand why this warning is being thrown. Even weirder is that the same warning is thrown when executing my RSpec test.

Any ideas of why is this happening? Am I missing something?

I couldn't find any questions on this neither on google nor on any issues, that's why I've created this one.

Thanks a bunch.

**Comment by roalcantara** [comment]
I'm observing the same behavior using the `3.0.0.pre1` version.

**Comment by takehiromouri** [comment]
I'm getting this as well with the same symptoms. It seems to happen when I use `render collection`
