### ISSUE TITLE
decorates_association :scope option should allow for multiple scopes

### ISSUE THREAD

**Issue by nhoffmann** [drapergem/draper#760]
If I understand it correctly, you can only pass one `scope` to `decorates_association` currently.
It would be nice if the `scope` option would accept an array of scopes. 

I would be happy to supply  a PR if this is something that other people want.
If there is already a way how this can be done, please let me know 😃

**Comment by novikserg** [comment]
@nhoffmann there is a `decorates_association` method that does exactly what you need:
https://github.com/drapergem/draper/blob/b2f9f085556771603104243e69d3992faf4b8af6/lib/draper/decorator.rb#L124

**Comment by seanlinsley** [comment]
👍 feel free to submit a PR

**Comment by codebycliff** [comment]
@nhoffmann If I'm understanding your request correctly, I believe this is supported through `decorates_associations`. This simply calls `decorate_association` for each association passed in.

I'm going to close this issue for now. If I'm not understanding you correctly, please comment and I'll look at re-opening the issue.
