### ISSUE TITLE
Name clash with private methods

### ISSUE THREAD

**Issue by fxn** [drapergem/draper#771]
I solved a weird bug this week in an application. Draper was working correctly, but this application hit what could be a gotcha in `delegate_all`. I open this issue to explain it, and to ask if you'd like me to volunteer a doc patch. Let me explain.

The situation was:

```ruby
class JobDecorator < Draper::Decorator
  delegate :final, to: :location, prefix: true
  delegate_all

  private
  def location
    (model.location || Location.new).decorate
  end
end

class LocationDecorator < Draper::Decorator
  def link_to_google_maps
    ...
  end
end
```

The symptom was that you deployed, everything was fine, and after some minutes

```ruby
job.decorate.location_final.link_to_google_maps
```

crashed with a `NoMethodError`, saying `Location` objects do not respond to `link_to_google_maps` (I am making the names up). How on earth is `job.decorate.location_final` returning all of a sudden a `Location` instead of a `LocationDecorator`?

Problem is, `Job` instances have `location` in their public interface. When the app launches, `JobDecorator` has a private method called `location`, but as soon as someone invokes `job.decorate.location`, the `method_missing` is triggered because `location` is not a public method of the decorator, so it is (correctly) forwarded **and** redefined/cached in the decorator class. The private method is gone.

That was the bug, but once understood, the problem is in the implementation of the decorator, because `delegate_all` effectively (lazily) injects the public interface of `Job` into `JobDecorator`, so this is as if you were writing by hand both a public and a private method with the same name. And the last one wins.

My solution has been to adopt the convention of naming private methods with a leading underscore. That way you are forward-compatible with any public method in `Job`, since conventionally Ruby programmers do not put leading underscores in public methods.

Do you think it would be good to document this gotcha? Something like "Beware `delegate_all` injects the current and future public APIs of the model in here, make sure the name of any private methods in the decorator do not clash. A leading underscore is a forward-compatible convention to ensure that."

**Comment by fxn** [comment]
Alternatively, if delegating to a method that clashes with an existing one in the decorator, perhaps you could raise. But gauging whether that is a good idea is more difficult for me, would need to have more perspective about usage of Draper out there. You are in a better position to choose.

**Comment by seanlinsley** [comment]
I think it'd make sense to raise an error.

**Comment by codebycliff** [comment]
Fixed by: https://github.com/drapergem/draper/pull/849
