### ISSUE TITLE
Abadoned?

### ISSUE THREAD

**Issue by caseyprovost** [drapergem/draper#772]
Haven't seen any traction here for 6 months now and our Rails 5 peeps are left to monkey patches, forking, or transitioning to other gems. Do you ya'll need help maintaining this?

**Comment by Deekor** [comment]
Trying to update our app from Rails 4.2.5 to 5.0.1 and running into an issue here is as well. What workarounds do you know of @caseyprovost ?

**Comment by caseyprovost** [comment]
@Deekor to be honest I am using this fork: 

```
gem 'draper', git: 'https://github.com/audionerd/draper.git', branch: 'rails5'
```

If this isn't fixed soon though we will likely remove it from the app in favor of ActiveModel serializers for API stuff and plain ol' ruby objects for simple decoration.

**Comment by Deekor** [comment]
@caseyprovost Interesting I'll look into it.

Getting the latest version via:

    gem 'draper', "3.0.0.pre1"

Seems to have fixed my issues for now.

**Comment by seanlinsley** [comment]
It's not abandoned. If anyone is interesting in becoming a maintainer please let me know.
