### ISSUE TITLE
NameError: uninitialized constant for Rails 5

### ISSUE THREAD

**Issue by vill** [drapergem/draper#773]
Hi there.  

```
Ruby 2.3.1p112
Rails 5.0.1
draper 3.0.0.pre1
```

`app/models/client/company/deal.rb`
```
module Client
  class Company
    class Deal < ApplicationRecord
      ....
    end
  end
end
```

`app/decorators/client/company/deal_decorator.rb`
```
module Client
  class Company
    class DealDecorator < Draper::Decorator
      delegate_all
      ....
    end
  end
end
```
For `Client::Company::Deal.all.decorate` or `Client::Company::DealDecorator.decorate_collection(Client::Company::Deal.all)` I am getting the following error in the production environment:
```
NameError: uninitialized constant #<Class:0xb65df564>::DealsDecorator
Did you mean?  Client::Company::DealDecorator
```
This error occurs when the following settings:
```
config.cache_classes = true
config.eager_load    = true
```
Everything works fine if I set the following in the `config/environments/production.rb`:
```
config.enable_dependency_loading = true
```
See the [config.enable_dependency_loading](https://github.com/rails/rails/commit/80b416f5e692ae79f4062f59fed6c7d7648a8af0) for details.

**Comment by HermannHH** [comment]
@vill I'm experiencing this exact same issue. My application works fine in development but fails when deployed to Heroku. I posted a S/O question [http://stackoverflow.com/questions/41583880/error-in-heroku-when-using-rails-5-and-draper-namespace](here). Hopefully someone knows how to fix this. I've tried numerous different solutions.

**Comment by vill** [comment]
@HermannHH, I fix this error so: 
```
@deals = Client::Company::Deal.all.map(&:decorate)
```

**Comment by spike886** [comment]
I had the same problem and solved adding this code to the decorators that have namespaces:
```
def self.collection_decorator_class
    Draper::CollectionDecorator
  end
```

**Comment by codebycliff** [comment]
This was merged in https://github.com/drapergem/draper/pull/795. Closing this now.
