### ISSUE TITLE
Fix indeterminate test causing builds to fail randomly

### ISSUE THREAD

**Issue by codebycliff** [drapergem/draper#784]
There is one test that fails randomly on Travis:

![image](https://cloud.githubusercontent.com/assets/651946/24421211/0b0429e2-13bb-11e7-9462-2c06eaa74c87.png)

There doesn't seem to be any obvious correlation between the failed builds (e.g. ruby version). You can check the various failed builds [here](https://travis-ci.org/drapergem/draper/builds). Just about every single failed build is due to this one specific test.

**Comment by varyonic** [comment]
Try [rspec --bisect --seed 22655](http://blog.arkency.com/2016/02/how-rspec-helped-me-with-resolving-random-spec-failures/)?

**Comment by codebycliff** [comment]
Tried that to no avail. I also tried the above command (`bin/rails test test/decorators/test_unit/helpers_test.rb`), with the seeds from various failed builds. I cannot seem to reproduce this locally at all. This is really hindering productivity and making hard to actually see at a glance which pull requests actually have builds failing. I'm tempting to comment out / skip the test until I can come back and look into it more. What do you think @varyonic?

**Comment by varyonic** [comment]
@deivid-rodriguez Thoughts?

**Comment by deivid-rodriguez** [comment]
@varyonic `rspec --bisect --seed 22655` is exactly what I would have tried. If the failure is not just order dependent but completely flaky then it requires deeper investigation...

@codebycliff If this is blocking other working you are doing and you currently have no time to investigate, I think your approach is right. Skip it with a big TODO and a firm intention of not letting it stagnate there :)

**Comment by codebycliff** [comment]
Thanks for your guy's input. I will skip the test for the time being and leave the issue open.

**Comment by codebycliff** [comment]
Nevermind. Skipping the test that I though was the culprit, just made another test in that suite fail. I'm not sure what to do from here.

**Comment by varyonic** [comment]
When all else fails `rspec --order defined`

**Comment by deivid-rodriguez** [comment]
@codebycliff Well, now you have more knowledge about the problem... That's good.

@varyonic As I understand it, this is not order related so running the tests in order might not help. But it's worth a try I guess.

There's something I don't understand though. Draper's tests seem to use RSpec, but the failure looks like Minitest... Does the test suite run the generated application test suite somehow?

**Comment by codebycliff** [comment]
Yes, it does from what I understand. The library itself provides test integration with RSpec and Minitest. The dummy application tests both integrations.

**Comment by codebycliff** [comment]
This has been fixed with https://github.com/drapergem/draper/pull/791. It's actually pretty silly what it ended up being.

**Comment by deivid-rodriguez** [comment]
Fantastic job! :heart_eyes: 

It seems pretty bad that tests have to depend so heavily on their description. In RSpec one would use tags for this, but most likely Minitest doesn't support something like that out of the box.

Anyways, again, fantastic job!
