### ISSUE TITLE
Draper doesn't work with Pundit out of the box.

### ISSUE THREAD

**Issue by codebycliff** [drapergem/draper#797]
When using the pundit gem, we are not able call `policy` related methods on our decorated objects. This seems to be a delegation issue. Here is an example:

```ruby
client = Client.first.decorate
if policy(client).enabled?
  puts "enabled"
end
```

Blows up with:

![image](https://cloud.githubusercontent.com/assets/651946/24717879/8a560cd0-19f9-11e7-9e1c-0bd1cc8c18b3.png)

While this is a `Pundit` error, I believe it is Draper's fault as a decorated object should act as an undecorated object.

**Comment by syguer** [comment]
hmm...
https://github.com/elabs/pundit/blob/c3f2d09a0e67e868449e4d53301dfdc819004032/lib/pundit/policy_finder.rb#L59

It looks succeeding to find policy name ( =`ClientPolicy`), but maybe failing to `constantize`.
Can `ClientPolicy` load from anywhere?

**Comment by codebycliff** [comment]
This was in fact a load path issue. Closing now.
