### ISSUE TITLE
Draper conflicts with another generator

### ISSUE THREAD

**Issue by Frexuz** [drapergem/draper#811]
I get an error when running a generator from the [mountain_view](https://github.com/devnacho/mountain_view) gem.
`mountain_view-0.12.0/lib/mountain_view/engine.rb:34:in block (2 levels) in <class:Engine>': undefined methodhelper' for ActionController::API:Class (NoMethodError)`

**If I remove Draper, that generator works just fine.** So it *seems* like a Draper issue? But I'm not sure.

Issue discussion over at **mountain_view**:
https://github.com/devnacho/mountain_view/issues/51

Any ideas?

**Comment by codebycliff** [comment]
Thanks for reporting this. After reading it over, I could see how this could be related to Draper. However, I wasn't able to reproduce it with a brand new app with Draper and mountain_view. Is the app in question in fact API only? Is it possible to get a sample app that reproduces the issue?

**Comment by Frexuz** [comment]
Tested again. 

```
ruby '2.3.1'

source 'https://rubygems.org'

gem 'rails', '5.1.0'
gem 'listen', '~> 3.0.5'
gem 'sqlite3'
gem 'puma'

gem 'mountain_view'
gem 'draper'
gem 'activeadmin'
```

Seems activeadmin is included in the collision.

- mountainview + draper works
- mountainview + activeadmin works
- mountainview + draper + activeadmin **does not**

Can you reproduce it this scenario?

Very strange. I'll post over at activeadmin as well :)

**Comment by Frexuz** [comment]
Fixed by https://github.com/devnacho/mountain_view/pull/53
