### ISSUE TITLE
Decorator can not access controller helper in test

### ISSUE THREAD

**Issue by swelther** [drapergem/draper#813]
Today I noticed a weird behaviour during my request spec:

The controller defines a helper method which is called from the decorator. But during the test this helper is not available.

Please see this gist with a sample app that reproduces the problem, using Ruby 2.3.3:

https://gist.github.com/swelther/47c5ffb707ca1145ca87d1dfb8aa99fa

My real world app uses RSpec instead of Minitest, but the result is the same.

Shouldn't it be possible to access helpers defined in the controller? What can I do to fix this?

**Comment by codebycliff** [comment]
Thanks for reporting this issue. It looks like it has been around for a while. It appears to have to do with the `ViewContext` not being cleared after each spec. I'll look into this and get back to you.

**Comment by Alexander-Senko** [comment]
1. I've got the same result after modernizing the gist for `master` and latest Rails.

2. After a lot of debugging and digging in, it appeared that Draper initializers don't get run for some reason. Thus, adding one to the gist fixes the issue:

```ruby
ActiveSupport.on_load :action_controller do
  Draper.setup_action_controller self
end
```
