### ISSUE TITLE
Misleading Error Message: Could not infer a decorator for ActiveRecord::Base.

### ISSUE THREAD

**Issue by pascalbetz** [drapergem/draper#819]
Since `decorator_class` recursevly walks up the class hierarchy to find a decorator the error is misleading and does not show the real class name. As an example:

```ruby
thing = MyCoolProject::CoolThing.new(...)
thing.decorate
```

will raise following error when decorator can not be found

> Could not infer a decorator for ActiveRecord::Base.

instead of

> Could not infer a decorator for MyCoolProject::CoolThing

Not a big issue as I usually now what I'm decorating...but I'm a big fan of helpful error messages:-)

I can provide a fix if this is of interest.

**Comment by syguer** [comment]
Related https://github.com/drapergem/draper/issues/767

**Comment by swelther** [comment]
I get this misleading error every now and then. Really annoying, would be happy for a fix :blush:

**Comment by pascalbetz** [comment]
@swelther I created a PR, feedback welcome!

**Comment by codebycliff** [comment]
Closing. This was fixed in #821.

**Comment by codebycliff** [comment]
This has been released to RubyGems.

**Comment by masciugo** [comment]
I had to add to point to github
`gem 'draper', github: 'drapergem/draper'`

to have it working

**Comment by vnhnhm** [comment]
As stated in the docs, it might help if nothing else works:

```ruby
@widget = ProductDecorator.new(Widget.first)
# or, equivalently
@widget = ProductDecorator.decorate(Widget.first)
```
