### ISSUE TITLE
STI error

### ISSUE THREAD

**Issue by DemidenkoAndrey** [drapergem/draper#822]
I have updated from '3.0.0.pre1' to '3.0.0' and have issue with STI.
I have STI  models and declare draper on original model. And when I decorate object I get errors that  
"uninitialized constant #<Class:0x0000000005ad7e38>::STI_class_nameDecorator"

**Comment by codebycliff** [comment]
Can you verify that this isn't fixed in master? We just fixed a similar issue, so I want to double check before looking into it. Thanks!

**Comment by DemidenkoAndrey** [comment]
@codebycliff Thank you. In master is everything ok.

**Comment by codebycliff** [comment]
Good deal! I'll get a release out here soon so you can update.
