### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by marcioJesus** [drapergem/draper#830]
Hi,

Can Add activesupport 5.2 support?

Thanks

**Comment by codebycliff** [comment]
What specific issue are you running into? Draper's dependency constraint on `activesupport` is `~> 5.0` which covers all versions up to `6.0`. Unless I'm missing something, there shouldn't be any dependency issues with Draper when upgrading to Rails 5.2. I just upgraded an application with Draper to Rails 5.2 yesterday without any issue. Sorry if I'm missing something.

**Comment by marcioJesus** [comment]
Oops, that's right. :) After your comment I realized that the problem is in another gem that prevented the update of activesupport

Thanks for the feedback. I'll close the issue
