### ISSUE TITLE
Add navigation for the knowledge center

### ISSUE THREAD

**Issue by toddoxford** [drapergem/draper#833]
Add link to the footer, header and console

301 redirect /knowledgecentre & /knowledgecentre/insuranceforondemandworkers to /knowlwdge_base

**Comment by roryokane** [comment]
Did you post this in the wrong place? I looked around, but couldn’t find any knowledge center related to the Draper gem. It has nothing to do with insurance either.

**Comment by codebycliff** [comment]
Yeah, this is definitely in the wrong place.
