### ISSUE TITLE
Compatibility with Rails 5.2

### ISSUE THREAD

**Issue by rusikf** [drapergem/draper#834]
Last version of draper 3.0.1 requires action pack 5.0, but we have already 5.2.1 for rails 5.2. Is it possible to update gemspec ?

**Comment by codebycliff** [comment]
Can you show me what exactly you are experiencing? The `actionpack` version in the gemspec is `~> 5.0` which resolves to _any_ version less that 6.0. See [this issue](https://github.com/drapergem/draper/issues/830) and [this issue](https://github.com/drapergem/draper/issues/808) for more detail.

**Comment by thomasdarde** [comment]
This is a mistake I think, draper appears first sometimes when trying to update rails , but it doesn't mean it's the gem blocking the update.

Ex, here :
```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    draper (~> 3.0.0) was resolved to 3.0.1, which depends on
      actionpack (~> 5.0)

    haml-rails was resolved to 1.0.0, which depends on
      actionpack (>= 4.0.1)

    inherited_resources (~> 1.8.0) was resolved to 1.8.0, which depends on
      actionpack (<= 5.2, >= 4.2)
```

It's inherited_resources that makes the update to 5.2.1 not working.

**Comment by rusikf** [comment]
@codebycliff I agree with @thomasdarde , when I run bundle update rails draper, i see:
```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    draper was resolved to 3.0.1, which depends on
      actionpack (~> 5.0)
```

**Comment by codebycliff** [comment]
I believe @thomasdarde is agreeing with my comment. Please correct me if I'm wrong @thomasdarde. Draper supports all versions of Rails less than 6. I have had Draper 3.0.1 running with Rails 5.2.1 for quite a while now. Is that the only output?  Can you provide me any more detail, such as the Gemfile?

**Comment by thomasdarde** [comment]
I do agree with @codebycliff 
@rusikf , you should share with us the whole bundle update output and you will see it's another gem that is blocking. 
I think this issue can be closed

**Comment by codebycliff** [comment]
@rusikf I'm going to close this for now. If you comment with more detail, I can help you look into it more.
