### ISSUE TITLE
not working with pagy gem

### ISSUE THREAD

**Issue by KozakIvan** [drapergem/draper#842]
undefined method `offset' for #<Draper::CollectionDecorator:0x000055c4dc57d0b8>

i'm doing as describe https://github.com/drapergem/draper/issues/429, but view can't find methods used in parent decorator.

**Comment by joshmn** [comment]
did you ever figure this out?

**Comment by codebycliff** [comment]
Can you try this on the latest version of Draper? I _think_ this should have been resolved by https://github.com/drapergem/draper/pull/845.

**Comment by codebycliff** [comment]
@KozakIvan I'm going to close this as I believe this issue has been resolved. If you find otherwise, please re-open the issue and I'll take a look.

**Comment by akz92** [comment]
I believe there's still some incompatibilities here as Pagy doesn't paginate properly a decorated collection but works fine if I remove the `decorate` statement.

**Comment by RTJ** [comment]
I have same problem.

**Comment by bodrovis** [comment]
To overcome this issue, you must perform decoration in two steps:

```ruby
    @pagy, @answers = pagy @question.answers.order(created_at: :desc)
    @answers = @answers.decorate
```

However, this won't work:

```ruby
    @pagy, @answers = pagy @question.answers.order(created_at: :desc).decorate
```
