### ISSUE TITLE
Ruby 2.7.0 support

### ISSUE THREAD

**Issue by kapso** [drapergem/draper#869]
Seeing this warning...

`lib/ruby/gems/2.7.0/gems/draper-3.1.0/lib/draper/delegation.rb:10: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

**Comment by pedrofurtado** [comment]
@olleolleolle @codebycliff 🤝

**Comment by codebycliff** [comment]
Fixed by: https://github.com/drapergem/draper/pull/870
