### ISSUE TITLE
So, 4.0.0 release requires rails 5.0 or 5.2?

### ISSUE THREAD

**Issue by biow0lf** [drapergem/draper#873]
Hi,

In `README.md`:

```
As of version 4.0.0, Draper only officially supports Rails 5.2
```

But, in `draper.gemspec`:

```
s.add_dependency 'activesupport', '>= 5.0'
s.add_dependency 'actionpack', '>= 5.0'
s.add_dependency 'activemodel', '>= 5.0'
```

So, how it right? README.md or gemspec?

**Comment by codebycliff** [comment]
Great point. My _intent_ here was to drop official support for Rails < 5.2 as Rails no longer supports versions less than 5.2. However, I didn't want to prevent people from using the gem on older versions of Rails as there are _currently_ no known issues preventing you from doing so. Does that make sense or am I crazy? I lean toward just updating the README to explain that better, but certainly could change the gemspec if that makes more sense.
