### ISSUE TITLE
NoMethodError: private method `expire_primary_index' called

### ISSUE THREAD

**Issue by saiqulhaq** [drapergem/draper#876]
I don't know this issue is caused by Identity cache or Draper gem so I post this issue to both repos

https://github.com/Shopify/identity_cache/blob/98dfa6eb13f9af9773e313ac202e83aab87d5eff/lib/identity_cache/parent_model_expiration.rb#L47

https://github.com/drapergem/draper/blob/4439ed8e84fd2af49f0df45fa21d7daf887b93ce/lib/draper/automatic_delegation.rb#L9

```

File /var/www/app/shared/bundle/ruby/2.5.0/gems/draper-4.0.0/lib/draper/automatic_delegation.rb line 10 in method_missing
File /var/www/app/shared/bundle/ruby/2.5.0/bundler/gems/identity_cache-c4799ac93b48/lib/identity_cache/parent_model_expiration.rb line 47 in block in expire_parent_caches
File /home/app/.rbenv/versions/2.5.5/lib/ruby/2.5.0/set.rb line 338 in each_key
File /home/app/.rbenv/versions/2.5.5/lib/ruby/2.5.0/set.rb line 338 in each
```

this was happening when trying to create a record
but succeed after submit my form again

https://github.com/Shopify/identity_cache/issues/441

**Comment by springerigor** [comment]
@saiqulhaq I guess you need to wait for 4.0.1 or downgrade draper temporary. I encountered a similar problem and patch has already been merged: https://github.com/drapergem/draper/pull/875

**Comment by saiqulhaq** [comment]
ok thanks
