### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by haffla** [drapergem/draper#902]
Can we have a new release? Last one is almost a year ago. Right now draper is not working with Ruby 3 when using for example `h.t('some_key', user_name: 'Jack')`. https://github.com/drapergem/draper/commit/9cb42f6e714764c1b196f49754328132bcc7ed32 fixed this.

**Comment by tisba** [comment]
That would indeed be very great. What's necessary to cut a release? Is there something you need help with?

**Comment by patricklindsay** [comment]
I'm happy to help in order to get a new release which supports Ruby 3. cc @codebycliff

**Comment by tisba** [comment]
gently-ping @codebycliff

**Comment by reedstonefood** [comment]
Hey @codebycliff 👋 if you could find some time to release a new version for the many users of this gem, it would be much appreciated. It's been over a year and there are some useful changes in here that people are eager to see, including Ruby 3 compatability. Thanks!

**Comment by codebycliff** [comment]
I'm sorry everyone, I will get around to this by the end of the weekend. I apologize for the delay – I don't have the same amount of time to dedicate to this gem as I once did. If anyone like to volunteer to help maintain the repository going forward, I would certainly appreciate the help.

**Comment by codebycliff** [comment]
New version has been released! Sorry again for the delay.

**Comment by tovodeverett** [comment]
Woohoo!!!  I just wanted to thank everyone who contributed and to thank @codebycliff for getting it out the door.  I've been on both sides of the fence over the years - the hardest thing in the world is finding the energy to support something that is no longer really in your core area of responsibility, but it's also demoralizing to put energy into contributing and to find it stalled or ignored by an owner that no longer has time to manage it.  I definitely don't have the skills or time to manage something with as many subtleties as `draper`, so I'm cheering on from the sidelines anyone who is willing to step in and demonstrate to @codebycliff that they can handle the reins!
