### ISSUE TITLE
Breaks respond_with in Rails API apps

### ISSUE THREAD

**Issue by heaven** [drapergem/draper#905]
The gem includes `ActionView::Rendering` to the `API` controllers, which breaks `respond_to`. I'm not sure whether this is an issue in the Draper gem or the Responders gem should find a more reliable way to handle this than checking for the inclusion of `ActionView::Rendering`. But these two gems don't work together.

## References

* https://github.com/heartcombo/responders/issues/154
* https://github.com/rails/rails/issues/27211#issuecomment-358028877
* #793

**Comment by DSKonstantin** [comment]
Any ideas?

**Comment by Alexander-Senko** [comment]
I hope, I could find a way not to include `ActionView::Rendering` into `ActionController::API` 🤔

**Comment by Alexander-Senko** [comment]
Duplicates #860.
