### ISSUE TITLE
ArgumentError using helpers with Ruby 3

### ISSUE THREAD

**Issue by CaioFML** [drapergem/draper#906]
Hello guys, I upgraded my Ruby for 3.0 from 2.7 and I'm having some troubles.

I have this helper in application_helper.rb:

```ruby
  def format_datetime(date, format: :small)
    I18n.l(date, format: format)
  rescue I18n::ArgumentError
    nil
  end
```

And when I call this method h.format_datetime with format like:
```ruby
  def expire_at(format: :small)
    format_datetime(object.expire_at, format: format)
  end
```

I receive:

![image](https://user-images.githubusercontent.com/37879125/111837611-e87fca80-88d6-11eb-8a10-3c79b0e19101.png)

But it works if I extract to a private method in draper, any thoughts?

**Comment by brian-kephart** [comment]
Using the current version of Draper from RubyGems results in errors like these. Support for Ruby 3 kwargs was added to git, but has not been released yet. Try installing directly from Github and see if the issue disappears.

```ruby
# Gemfile
gem 'draper', github: 'drapergem/draper'
```

@codebycliff is there anything blocking a new minor/patch release for Ruby 3 support?

**Comment by CaioFML** [comment]
> Using the current version of Draper from RubyGems results in errors like these. Support for Ruby 3 kwargs was added to git, but has not been released yet. Try installing directly from Github and see if the issue disappears.
> 
> ```ruby
> # Gemfile
> gem 'draper', github: 'drapergem/draper'
> ```
> 
> @codebycliff is there anything blocking a new minor/patch release for Ruby 3 support?

Yeah, it works, thanks!

Waiting for the release for ruby 3 support! :)

**Comment by tisba** [comment]
See https://github.com/drapergem/draper/issues/902

**Comment by mishina2228** [comment]
@CaioFML v4.0.2 has been released, so I think we can close this issue.
cc @codebycliff
