### ISSUE TITLE
Unexpected behavior when `frozen?` method is defined in model

### ISSUE THREAD

**Issue by kenzo-tanaka** [drapergem/draper#918]
Hi👋
First of all thank you for the very helpful gem!
I found an unexpected behavior while using draper and would like to report it.
When the `frozen?` method is defined in the model, the decorated instance returns false.

The following is a sample code.

```rb
# app/models/user.rb

class User < ApplicationRecord
  def frozen?
    true
  end
end
```

```rb
class UserDecorator < Draper::Decorator
  delegate_all
end
```

```shell
rails console
irb(main):001:0> User.first.decorate.frozen?
   (1.2ms)  SELECT sqlite_version(*)
  User Load (0.2ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> false  # expected true
```

https://github.com/kenzo-tanaka/tmp_draper

I'm sorry if I misunderstood something about this behaviour🙏

**Comment by itzbernoulli** [comment]
Hi @kenzo-tanaka seems this is a ruby thing rather than a draper issue. If you call frozen? on the object without decorating it still returns false as long as you didn't freeze the object.

**Comment by Alexander-Senko** [comment]
See [Object#frozen?](https://docs.ruby-lang.org/en/2.4.0/Object.html#method-i-frozen-3F).

`#delegate_all` won't redefine existing methods.

One still can delegate / redefine this method explicitly in the decorator.
